// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7vx690t-ffg1927-2,HLS_INPUT_CLOCK=6.250000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.237375,HLS_SYN_LAT=14,HLS_SYN_TPT=4,HLS_SYN_MEM=210,HLS_SYN_DSP=0,HLS_SYN_FF=165062,HLS_SYN_LUT=759471,HLS_VERSION=2020_1}" *)

module myproject (
        link_in_0_V,
        link_in_1_V,
        link_in_2_V,
        link_in_3_V,
        link_in_4_V,
        link_in_5_V,
        link_in_6_V,
        link_in_7_V,
        link_in_8_V,
        link_in_9_V,
        link_in_10_V,
        link_in_11_V,
        link_in_12_V,
        link_in_13_V,
        link_in_14_V,
        link_in_15_V,
        link_in_16_V,
        link_in_17_V,
        link_in_18_V,
        link_in_19_V,
        link_in_20_V,
        link_in_21_V,
        link_in_22_V,
        link_in_23_V,
        link_in_24_V,
        link_in_25_V,
        link_in_26_V,
        link_in_27_V,
        link_in_28_V,
        link_in_29_V,
        link_in_30_V,
        link_in_31_V,
        link_in_32_V,
        link_in_33_V,
        link_in_34_V,
        link_in_35_V,
        link_out_0_V_i,
        link_out_0_V_o,
        ap_clk,
        ap_rst,
        ap_start,
        link_out_0_V_o_ap_vld,
        ap_done,
        ap_ready,
        ap_idle
);


input  [127:0] link_in_0_V;
input  [127:0] link_in_1_V;
input  [127:0] link_in_2_V;
input  [127:0] link_in_3_V;
input  [127:0] link_in_4_V;
input  [127:0] link_in_5_V;
input  [127:0] link_in_6_V;
input  [127:0] link_in_7_V;
input  [127:0] link_in_8_V;
input  [127:0] link_in_9_V;
input  [127:0] link_in_10_V;
input  [127:0] link_in_11_V;
input  [127:0] link_in_12_V;
input  [127:0] link_in_13_V;
input  [127:0] link_in_14_V;
input  [127:0] link_in_15_V;
input  [127:0] link_in_16_V;
input  [127:0] link_in_17_V;
input  [127:0] link_in_18_V;
input  [127:0] link_in_19_V;
input  [127:0] link_in_20_V;
input  [127:0] link_in_21_V;
input  [127:0] link_in_22_V;
input  [127:0] link_in_23_V;
input  [127:0] link_in_24_V;
input  [127:0] link_in_25_V;
input  [127:0] link_in_26_V;
input  [127:0] link_in_27_V;
input  [127:0] link_in_28_V;
input  [127:0] link_in_29_V;
input  [127:0] link_in_30_V;
input  [127:0] link_in_31_V;
input  [127:0] link_in_32_V;
input  [127:0] link_in_33_V;
input  [127:0] link_in_34_V;
input  [127:0] link_in_35_V;
input  [127:0] link_out_0_V_i;
output  [127:0] link_out_0_V_o;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   link_out_0_V_o_ap_vld;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    Block_codeRepl320123_proc_U0_ap_start;
wire    Block_codeRepl320123_proc_U0_ap_done;
wire    Block_codeRepl320123_proc_U0_ap_continue;
wire    Block_codeRepl320123_proc_U0_ap_idle;
wire    Block_codeRepl320123_proc_U0_ap_ready;
wire   [2519:0] Block_codeRepl320123_proc_U0_ap_return;
wire    ap_channel_done_Inputs_V_channel;
wire    Inputs_V_channel_full_n;
wire    dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_start;
wire    dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done;
wire    dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_continue;
wire    dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_idle;
wire    dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_ready;
wire   [19:0] dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_0;
wire   [19:0] dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_1;
wire   [19:0] dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_2;
wire   [19:0] dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_3;
wire   [19:0] dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_4;
wire   [19:0] dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_5;
wire   [19:0] dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_6;
wire   [19:0] dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_7;
wire   [19:0] dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_8;
wire   [19:0] dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_9;
wire   [19:0] dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_10;
wire   [19:0] dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_11;
wire   [19:0] dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_12;
wire   [19:0] dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_13;
wire   [19:0] dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_14;
wire    ap_channel_done_layer2_out_14_V;
wire    layer2_out_14_V_full_n;
reg    ap_sync_reg_channel_write_layer2_out_14_V;
wire    ap_sync_channel_write_layer2_out_14_V;
wire    ap_channel_done_layer2_out_13_V;
wire    layer2_out_13_V_full_n;
reg    ap_sync_reg_channel_write_layer2_out_13_V;
wire    ap_sync_channel_write_layer2_out_13_V;
wire    ap_channel_done_layer2_out_12_V;
wire    layer2_out_12_V_full_n;
reg    ap_sync_reg_channel_write_layer2_out_12_V;
wire    ap_sync_channel_write_layer2_out_12_V;
wire    ap_channel_done_layer2_out_11_V;
wire    layer2_out_11_V_full_n;
reg    ap_sync_reg_channel_write_layer2_out_11_V;
wire    ap_sync_channel_write_layer2_out_11_V;
wire    ap_channel_done_layer2_out_10_V;
wire    layer2_out_10_V_full_n;
reg    ap_sync_reg_channel_write_layer2_out_10_V;
wire    ap_sync_channel_write_layer2_out_10_V;
wire    ap_channel_done_layer2_out_9_V;
wire    layer2_out_9_V_full_n;
reg    ap_sync_reg_channel_write_layer2_out_9_V;
wire    ap_sync_channel_write_layer2_out_9_V;
wire    ap_channel_done_layer2_out_8_V;
wire    layer2_out_8_V_full_n;
reg    ap_sync_reg_channel_write_layer2_out_8_V;
wire    ap_sync_channel_write_layer2_out_8_V;
wire    ap_channel_done_layer2_out_7_V;
wire    layer2_out_7_V_full_n;
reg    ap_sync_reg_channel_write_layer2_out_7_V;
wire    ap_sync_channel_write_layer2_out_7_V;
wire    ap_channel_done_layer2_out_6_V;
wire    layer2_out_6_V_full_n;
reg    ap_sync_reg_channel_write_layer2_out_6_V;
wire    ap_sync_channel_write_layer2_out_6_V;
wire    ap_channel_done_layer2_out_5_V;
wire    layer2_out_5_V_full_n;
reg    ap_sync_reg_channel_write_layer2_out_5_V;
wire    ap_sync_channel_write_layer2_out_5_V;
wire    ap_channel_done_layer2_out_4_V;
wire    layer2_out_4_V_full_n;
reg    ap_sync_reg_channel_write_layer2_out_4_V;
wire    ap_sync_channel_write_layer2_out_4_V;
wire    ap_channel_done_layer2_out_3_V;
wire    layer2_out_3_V_full_n;
reg    ap_sync_reg_channel_write_layer2_out_3_V;
wire    ap_sync_channel_write_layer2_out_3_V;
wire    ap_channel_done_layer2_out_2_V;
wire    layer2_out_2_V_full_n;
reg    ap_sync_reg_channel_write_layer2_out_2_V;
wire    ap_sync_channel_write_layer2_out_2_V;
wire    ap_channel_done_layer2_out_1_V;
wire    layer2_out_1_V_full_n;
reg    ap_sync_reg_channel_write_layer2_out_1_V;
wire    ap_sync_channel_write_layer2_out_1_V;
wire    ap_channel_done_layer2_out_0_V;
wire    layer2_out_0_V_full_n;
reg    ap_sync_reg_channel_write_layer2_out_0_V;
wire    ap_sync_channel_write_layer2_out_0_V;
wire    normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_start;
wire    normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done;
wire    normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_continue;
wire    normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_idle;
wire    normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_ready;
wire   [19:0] normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_0;
wire   [19:0] normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_1;
wire   [19:0] normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_2;
wire   [19:0] normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_3;
wire   [19:0] normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_4;
wire   [19:0] normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_5;
wire   [19:0] normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_6;
wire   [19:0] normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_7;
wire   [19:0] normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_8;
wire   [19:0] normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_9;
wire   [19:0] normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_10;
wire   [19:0] normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_11;
wire   [19:0] normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_12;
wire   [19:0] normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_13;
wire   [19:0] normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_14;
wire    ap_channel_done_layer4_out_14_V;
wire    layer4_out_14_V_full_n;
reg    ap_sync_reg_channel_write_layer4_out_14_V;
wire    ap_sync_channel_write_layer4_out_14_V;
wire    ap_channel_done_layer4_out_13_V;
wire    layer4_out_13_V_full_n;
reg    ap_sync_reg_channel_write_layer4_out_13_V;
wire    ap_sync_channel_write_layer4_out_13_V;
wire    ap_channel_done_layer4_out_12_V;
wire    layer4_out_12_V_full_n;
reg    ap_sync_reg_channel_write_layer4_out_12_V;
wire    ap_sync_channel_write_layer4_out_12_V;
wire    ap_channel_done_layer4_out_11_V;
wire    layer4_out_11_V_full_n;
reg    ap_sync_reg_channel_write_layer4_out_11_V;
wire    ap_sync_channel_write_layer4_out_11_V;
wire    ap_channel_done_layer4_out_10_V;
wire    layer4_out_10_V_full_n;
reg    ap_sync_reg_channel_write_layer4_out_10_V;
wire    ap_sync_channel_write_layer4_out_10_V;
wire    ap_channel_done_layer4_out_9_V;
wire    layer4_out_9_V_full_n;
reg    ap_sync_reg_channel_write_layer4_out_9_V;
wire    ap_sync_channel_write_layer4_out_9_V;
wire    ap_channel_done_layer4_out_8_V;
wire    layer4_out_8_V_full_n;
reg    ap_sync_reg_channel_write_layer4_out_8_V;
wire    ap_sync_channel_write_layer4_out_8_V;
wire    ap_channel_done_layer4_out_7_V;
wire    layer4_out_7_V_full_n;
reg    ap_sync_reg_channel_write_layer4_out_7_V;
wire    ap_sync_channel_write_layer4_out_7_V;
wire    ap_channel_done_layer4_out_6_V;
wire    layer4_out_6_V_full_n;
reg    ap_sync_reg_channel_write_layer4_out_6_V;
wire    ap_sync_channel_write_layer4_out_6_V;
wire    ap_channel_done_layer4_out_5_V;
wire    layer4_out_5_V_full_n;
reg    ap_sync_reg_channel_write_layer4_out_5_V;
wire    ap_sync_channel_write_layer4_out_5_V;
wire    ap_channel_done_layer4_out_4_V;
wire    layer4_out_4_V_full_n;
reg    ap_sync_reg_channel_write_layer4_out_4_V;
wire    ap_sync_channel_write_layer4_out_4_V;
wire    ap_channel_done_layer4_out_3_V;
wire    layer4_out_3_V_full_n;
reg    ap_sync_reg_channel_write_layer4_out_3_V;
wire    ap_sync_channel_write_layer4_out_3_V;
wire    ap_channel_done_layer4_out_2_V;
wire    layer4_out_2_V_full_n;
reg    ap_sync_reg_channel_write_layer4_out_2_V;
wire    ap_sync_channel_write_layer4_out_2_V;
wire    ap_channel_done_layer4_out_1_V;
wire    layer4_out_1_V_full_n;
reg    ap_sync_reg_channel_write_layer4_out_1_V;
wire    ap_sync_channel_write_layer4_out_1_V;
wire    ap_channel_done_layer4_out_0_V;
wire    layer4_out_0_V_full_n;
reg    ap_sync_reg_channel_write_layer4_out_0_V;
wire    ap_sync_channel_write_layer4_out_0_V;
wire    relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_start;
wire    relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done;
wire    relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_continue;
wire    relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_idle;
wire    relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_ready;
wire   [4:0] relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_0;
wire   [4:0] relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_1;
wire   [4:0] relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_2;
wire   [4:0] relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_3;
wire   [4:0] relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_4;
wire   [4:0] relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_5;
wire   [4:0] relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_6;
wire   [4:0] relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_7;
wire   [4:0] relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_8;
wire   [4:0] relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_9;
wire   [4:0] relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_10;
wire   [4:0] relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_11;
wire   [4:0] relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_12;
wire   [4:0] relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_13;
wire   [4:0] relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_14;
wire    ap_channel_done_layer5_out_14_V;
wire    layer5_out_14_V_full_n;
reg    ap_sync_reg_channel_write_layer5_out_14_V;
wire    ap_sync_channel_write_layer5_out_14_V;
wire    ap_channel_done_layer5_out_13_V;
wire    layer5_out_13_V_full_n;
reg    ap_sync_reg_channel_write_layer5_out_13_V;
wire    ap_sync_channel_write_layer5_out_13_V;
wire    ap_channel_done_layer5_out_12_V;
wire    layer5_out_12_V_full_n;
reg    ap_sync_reg_channel_write_layer5_out_12_V;
wire    ap_sync_channel_write_layer5_out_12_V;
wire    ap_channel_done_layer5_out_11_V;
wire    layer5_out_11_V_full_n;
reg    ap_sync_reg_channel_write_layer5_out_11_V;
wire    ap_sync_channel_write_layer5_out_11_V;
wire    ap_channel_done_layer5_out_10_V;
wire    layer5_out_10_V_full_n;
reg    ap_sync_reg_channel_write_layer5_out_10_V;
wire    ap_sync_channel_write_layer5_out_10_V;
wire    ap_channel_done_layer5_out_9_V;
wire    layer5_out_9_V_full_n;
reg    ap_sync_reg_channel_write_layer5_out_9_V;
wire    ap_sync_channel_write_layer5_out_9_V;
wire    ap_channel_done_layer5_out_8_V;
wire    layer5_out_8_V_full_n;
reg    ap_sync_reg_channel_write_layer5_out_8_V;
wire    ap_sync_channel_write_layer5_out_8_V;
wire    ap_channel_done_layer5_out_7_V;
wire    layer5_out_7_V_full_n;
reg    ap_sync_reg_channel_write_layer5_out_7_V;
wire    ap_sync_channel_write_layer5_out_7_V;
wire    ap_channel_done_layer5_out_6_V;
wire    layer5_out_6_V_full_n;
reg    ap_sync_reg_channel_write_layer5_out_6_V;
wire    ap_sync_channel_write_layer5_out_6_V;
wire    ap_channel_done_layer5_out_5_V;
wire    layer5_out_5_V_full_n;
reg    ap_sync_reg_channel_write_layer5_out_5_V;
wire    ap_sync_channel_write_layer5_out_5_V;
wire    ap_channel_done_layer5_out_4_V;
wire    layer5_out_4_V_full_n;
reg    ap_sync_reg_channel_write_layer5_out_4_V;
wire    ap_sync_channel_write_layer5_out_4_V;
wire    ap_channel_done_layer5_out_3_V;
wire    layer5_out_3_V_full_n;
reg    ap_sync_reg_channel_write_layer5_out_3_V;
wire    ap_sync_channel_write_layer5_out_3_V;
wire    ap_channel_done_layer5_out_2_V;
wire    layer5_out_2_V_full_n;
reg    ap_sync_reg_channel_write_layer5_out_2_V;
wire    ap_sync_channel_write_layer5_out_2_V;
wire    ap_channel_done_layer5_out_1_V;
wire    layer5_out_1_V_full_n;
reg    ap_sync_reg_channel_write_layer5_out_1_V;
wire    ap_sync_channel_write_layer5_out_1_V;
wire    ap_channel_done_layer5_out_0_V;
wire    layer5_out_0_V_full_n;
reg    ap_sync_reg_channel_write_layer5_out_0_V;
wire    ap_sync_channel_write_layer5_out_0_V;
wire    Block_codeRepl320123320129_proc72_U0_ap_start;
wire    Block_codeRepl320123320129_proc72_U0_ap_done;
wire    Block_codeRepl320123320129_proc72_U0_ap_continue;
wire    Block_codeRepl320123320129_proc72_U0_ap_idle;
wire    Block_codeRepl320123320129_proc72_U0_ap_ready;
wire   [127:0] Block_codeRepl320123320129_proc72_U0_link_out_0_V_o;
wire    Block_codeRepl320123320129_proc72_U0_link_out_0_V_o_ap_vld;
wire    ap_sync_continue;
wire   [2519:0] Inputs_V_channel_dout;
wire    Inputs_V_channel_empty_n;
wire   [19:0] layer2_out_0_V_dout;
wire    layer2_out_0_V_empty_n;
wire   [19:0] layer2_out_1_V_dout;
wire    layer2_out_1_V_empty_n;
wire   [19:0] layer2_out_2_V_dout;
wire    layer2_out_2_V_empty_n;
wire   [19:0] layer2_out_3_V_dout;
wire    layer2_out_3_V_empty_n;
wire   [19:0] layer2_out_4_V_dout;
wire    layer2_out_4_V_empty_n;
wire   [19:0] layer2_out_5_V_dout;
wire    layer2_out_5_V_empty_n;
wire   [19:0] layer2_out_6_V_dout;
wire    layer2_out_6_V_empty_n;
wire   [19:0] layer2_out_7_V_dout;
wire    layer2_out_7_V_empty_n;
wire   [19:0] layer2_out_8_V_dout;
wire    layer2_out_8_V_empty_n;
wire   [19:0] layer2_out_9_V_dout;
wire    layer2_out_9_V_empty_n;
wire   [19:0] layer2_out_10_V_dout;
wire    layer2_out_10_V_empty_n;
wire   [19:0] layer2_out_11_V_dout;
wire    layer2_out_11_V_empty_n;
wire   [19:0] layer2_out_12_V_dout;
wire    layer2_out_12_V_empty_n;
wire   [19:0] layer2_out_13_V_dout;
wire    layer2_out_13_V_empty_n;
wire   [19:0] layer2_out_14_V_dout;
wire    layer2_out_14_V_empty_n;
wire   [19:0] layer4_out_0_V_dout;
wire    layer4_out_0_V_empty_n;
wire   [19:0] layer4_out_1_V_dout;
wire    layer4_out_1_V_empty_n;
wire   [19:0] layer4_out_2_V_dout;
wire    layer4_out_2_V_empty_n;
wire   [19:0] layer4_out_3_V_dout;
wire    layer4_out_3_V_empty_n;
wire   [19:0] layer4_out_4_V_dout;
wire    layer4_out_4_V_empty_n;
wire   [19:0] layer4_out_5_V_dout;
wire    layer4_out_5_V_empty_n;
wire   [19:0] layer4_out_6_V_dout;
wire    layer4_out_6_V_empty_n;
wire   [19:0] layer4_out_7_V_dout;
wire    layer4_out_7_V_empty_n;
wire   [19:0] layer4_out_8_V_dout;
wire    layer4_out_8_V_empty_n;
wire   [19:0] layer4_out_9_V_dout;
wire    layer4_out_9_V_empty_n;
wire   [19:0] layer4_out_10_V_dout;
wire    layer4_out_10_V_empty_n;
wire   [19:0] layer4_out_11_V_dout;
wire    layer4_out_11_V_empty_n;
wire   [19:0] layer4_out_12_V_dout;
wire    layer4_out_12_V_empty_n;
wire   [19:0] layer4_out_13_V_dout;
wire    layer4_out_13_V_empty_n;
wire   [19:0] layer4_out_14_V_dout;
wire    layer4_out_14_V_empty_n;
wire   [4:0] layer5_out_0_V_dout;
wire    layer5_out_0_V_empty_n;
wire   [4:0] layer5_out_1_V_dout;
wire    layer5_out_1_V_empty_n;
wire   [4:0] layer5_out_2_V_dout;
wire    layer5_out_2_V_empty_n;
wire   [4:0] layer5_out_3_V_dout;
wire    layer5_out_3_V_empty_n;
wire   [4:0] layer5_out_4_V_dout;
wire    layer5_out_4_V_empty_n;
wire   [4:0] layer5_out_5_V_dout;
wire    layer5_out_5_V_empty_n;
wire   [4:0] layer5_out_6_V_dout;
wire    layer5_out_6_V_empty_n;
wire   [4:0] layer5_out_7_V_dout;
wire    layer5_out_7_V_empty_n;
wire   [4:0] layer5_out_8_V_dout;
wire    layer5_out_8_V_empty_n;
wire   [4:0] layer5_out_9_V_dout;
wire    layer5_out_9_V_empty_n;
wire   [4:0] layer5_out_10_V_dout;
wire    layer5_out_10_V_empty_n;
wire   [4:0] layer5_out_11_V_dout;
wire    layer5_out_11_V_empty_n;
wire   [4:0] layer5_out_12_V_dout;
wire    layer5_out_12_V_empty_n;
wire   [4:0] layer5_out_13_V_dout;
wire    layer5_out_13_V_empty_n;
wire   [4:0] layer5_out_14_V_dout;
wire    layer5_out_14_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_Block_codeRepl320123_proc_U0_ap_ready;
wire    ap_sync_Block_codeRepl320123_proc_U0_ap_ready;
reg   [1:0] Block_codeRepl320123_proc_U0_ap_ready_count;
reg    ap_sync_reg_Block_codeRepl320123320129_proc72_U0_ap_ready;
wire    ap_sync_Block_codeRepl320123320129_proc72_U0_ap_ready;
reg   [1:0] Block_codeRepl320123320129_proc72_U0_ap_ready_count;
wire    Block_codeRepl320123_proc_U0_start_full_n;
wire    Block_codeRepl320123_proc_U0_start_write;
wire    dense_resource_ap_ufixed_ap_fixed_config2_U0_start_full_n;
wire    dense_resource_ap_ufixed_ap_fixed_config2_U0_start_write;
wire    normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_start_full_n;
wire    normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_start_write;
wire    relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_start_full_n;
wire    relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_start_write;
wire    Block_codeRepl320123320129_proc72_U0_start_full_n;
wire    Block_codeRepl320123320129_proc72_U0_start_write;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_layer2_out_14_V = 1'b0;
#0 ap_sync_reg_channel_write_layer2_out_13_V = 1'b0;
#0 ap_sync_reg_channel_write_layer2_out_12_V = 1'b0;
#0 ap_sync_reg_channel_write_layer2_out_11_V = 1'b0;
#0 ap_sync_reg_channel_write_layer2_out_10_V = 1'b0;
#0 ap_sync_reg_channel_write_layer2_out_9_V = 1'b0;
#0 ap_sync_reg_channel_write_layer2_out_8_V = 1'b0;
#0 ap_sync_reg_channel_write_layer2_out_7_V = 1'b0;
#0 ap_sync_reg_channel_write_layer2_out_6_V = 1'b0;
#0 ap_sync_reg_channel_write_layer2_out_5_V = 1'b0;
#0 ap_sync_reg_channel_write_layer2_out_4_V = 1'b0;
#0 ap_sync_reg_channel_write_layer2_out_3_V = 1'b0;
#0 ap_sync_reg_channel_write_layer2_out_2_V = 1'b0;
#0 ap_sync_reg_channel_write_layer2_out_1_V = 1'b0;
#0 ap_sync_reg_channel_write_layer2_out_0_V = 1'b0;
#0 ap_sync_reg_channel_write_layer4_out_14_V = 1'b0;
#0 ap_sync_reg_channel_write_layer4_out_13_V = 1'b0;
#0 ap_sync_reg_channel_write_layer4_out_12_V = 1'b0;
#0 ap_sync_reg_channel_write_layer4_out_11_V = 1'b0;
#0 ap_sync_reg_channel_write_layer4_out_10_V = 1'b0;
#0 ap_sync_reg_channel_write_layer4_out_9_V = 1'b0;
#0 ap_sync_reg_channel_write_layer4_out_8_V = 1'b0;
#0 ap_sync_reg_channel_write_layer4_out_7_V = 1'b0;
#0 ap_sync_reg_channel_write_layer4_out_6_V = 1'b0;
#0 ap_sync_reg_channel_write_layer4_out_5_V = 1'b0;
#0 ap_sync_reg_channel_write_layer4_out_4_V = 1'b0;
#0 ap_sync_reg_channel_write_layer4_out_3_V = 1'b0;
#0 ap_sync_reg_channel_write_layer4_out_2_V = 1'b0;
#0 ap_sync_reg_channel_write_layer4_out_1_V = 1'b0;
#0 ap_sync_reg_channel_write_layer4_out_0_V = 1'b0;
#0 ap_sync_reg_channel_write_layer5_out_14_V = 1'b0;
#0 ap_sync_reg_channel_write_layer5_out_13_V = 1'b0;
#0 ap_sync_reg_channel_write_layer5_out_12_V = 1'b0;
#0 ap_sync_reg_channel_write_layer5_out_11_V = 1'b0;
#0 ap_sync_reg_channel_write_layer5_out_10_V = 1'b0;
#0 ap_sync_reg_channel_write_layer5_out_9_V = 1'b0;
#0 ap_sync_reg_channel_write_layer5_out_8_V = 1'b0;
#0 ap_sync_reg_channel_write_layer5_out_7_V = 1'b0;
#0 ap_sync_reg_channel_write_layer5_out_6_V = 1'b0;
#0 ap_sync_reg_channel_write_layer5_out_5_V = 1'b0;
#0 ap_sync_reg_channel_write_layer5_out_4_V = 1'b0;
#0 ap_sync_reg_channel_write_layer5_out_3_V = 1'b0;
#0 ap_sync_reg_channel_write_layer5_out_2_V = 1'b0;
#0 ap_sync_reg_channel_write_layer5_out_1_V = 1'b0;
#0 ap_sync_reg_channel_write_layer5_out_0_V = 1'b0;
#0 ap_sync_reg_Block_codeRepl320123_proc_U0_ap_ready = 1'b0;
#0 Block_codeRepl320123_proc_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_Block_codeRepl320123320129_proc72_U0_ap_ready = 1'b0;
#0 Block_codeRepl320123320129_proc72_U0_ap_ready_count = 2'd0;
end

Block_codeRepl320123_proc Block_codeRepl320123_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Block_codeRepl320123_proc_U0_ap_start),
    .ap_done(Block_codeRepl320123_proc_U0_ap_done),
    .ap_continue(Block_codeRepl320123_proc_U0_ap_continue),
    .ap_idle(Block_codeRepl320123_proc_U0_ap_idle),
    .ap_ready(Block_codeRepl320123_proc_U0_ap_ready),
    .link_in_0_V(link_in_0_V),
    .link_in_1_V(link_in_1_V),
    .link_in_2_V(link_in_2_V),
    .link_in_3_V(link_in_3_V),
    .link_in_4_V(link_in_4_V),
    .link_in_5_V(link_in_5_V),
    .link_in_6_V(link_in_6_V),
    .link_in_7_V(link_in_7_V),
    .link_in_8_V(link_in_8_V),
    .link_in_9_V(link_in_9_V),
    .link_in_10_V(link_in_10_V),
    .link_in_11_V(link_in_11_V),
    .link_in_12_V(link_in_12_V),
    .link_in_13_V(link_in_13_V),
    .link_in_14_V(link_in_14_V),
    .link_in_15_V(link_in_15_V),
    .link_in_16_V(link_in_16_V),
    .link_in_17_V(link_in_17_V),
    .link_in_18_V(link_in_18_V),
    .link_in_19_V(link_in_19_V),
    .link_in_20_V(link_in_20_V),
    .link_in_21_V(link_in_21_V),
    .link_in_22_V(link_in_22_V),
    .link_in_23_V(link_in_23_V),
    .link_in_24_V(link_in_24_V),
    .link_in_25_V(link_in_25_V),
    .link_in_26_V(link_in_26_V),
    .link_in_27_V(link_in_27_V),
    .link_in_28_V(link_in_28_V),
    .link_in_29_V(link_in_29_V),
    .link_in_30_V(link_in_30_V),
    .link_in_31_V(link_in_31_V),
    .link_in_32_V(link_in_32_V),
    .link_in_33_V(link_in_33_V),
    .link_in_34_V(link_in_34_V),
    .link_in_35_V(link_in_35_V),
    .ap_return(Block_codeRepl320123_proc_U0_ap_return)
);

dense_resource_ap_ufixed_ap_fixed_config2_s dense_resource_ap_ufixed_ap_fixed_config2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_start),
    .ap_done(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done),
    .ap_continue(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_continue),
    .ap_idle(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_idle),
    .ap_ready(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_ready),
    .data_V_read(Inputs_V_channel_dout),
    .ap_return_0(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_0),
    .ap_return_1(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_1),
    .ap_return_2(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_2),
    .ap_return_3(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_3),
    .ap_return_4(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_4),
    .ap_return_5(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_5),
    .ap_return_6(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_6),
    .ap_return_7(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_7),
    .ap_return_8(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_8),
    .ap_return_9(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_9),
    .ap_return_10(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_10),
    .ap_return_11(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_11),
    .ap_return_12(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_12),
    .ap_return_13(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_13),
    .ap_return_14(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_14)
);

normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_start),
    .ap_done(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done),
    .ap_continue(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_continue),
    .ap_idle(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_idle),
    .ap_ready(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_ready),
    .p_read(layer2_out_0_V_dout),
    .p_read1(layer2_out_1_V_dout),
    .p_read2(layer2_out_2_V_dout),
    .p_read3(layer2_out_3_V_dout),
    .p_read4(layer2_out_4_V_dout),
    .p_read5(layer2_out_5_V_dout),
    .p_read6(layer2_out_6_V_dout),
    .p_read7(layer2_out_7_V_dout),
    .p_read8(layer2_out_8_V_dout),
    .p_read9(layer2_out_9_V_dout),
    .p_read10(layer2_out_10_V_dout),
    .p_read11(layer2_out_11_V_dout),
    .p_read12(layer2_out_12_V_dout),
    .p_read13(layer2_out_13_V_dout),
    .p_read14(layer2_out_14_V_dout),
    .ap_return_0(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_0),
    .ap_return_1(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_1),
    .ap_return_2(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_2),
    .ap_return_3(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_3),
    .ap_return_4(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_4),
    .ap_return_5(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_5),
    .ap_return_6(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_6),
    .ap_return_7(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_7),
    .ap_return_8(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_8),
    .ap_return_9(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_9),
    .ap_return_10(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_10),
    .ap_return_11(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_11),
    .ap_return_12(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_12),
    .ap_return_13(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_13),
    .ap_return_14(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_14)
);

relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_s relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_start),
    .ap_done(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done),
    .ap_continue(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_continue),
    .ap_idle(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_idle),
    .ap_ready(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_ready),
    .data_0_V_read(layer4_out_0_V_dout),
    .data_1_V_read(layer4_out_1_V_dout),
    .data_2_V_read(layer4_out_2_V_dout),
    .data_3_V_read(layer4_out_3_V_dout),
    .data_4_V_read(layer4_out_4_V_dout),
    .data_5_V_read(layer4_out_5_V_dout),
    .data_6_V_read(layer4_out_6_V_dout),
    .data_7_V_read(layer4_out_7_V_dout),
    .data_8_V_read(layer4_out_8_V_dout),
    .data_9_V_read(layer4_out_9_V_dout),
    .data_10_V_read(layer4_out_10_V_dout),
    .data_11_V_read(layer4_out_11_V_dout),
    .data_12_V_read(layer4_out_12_V_dout),
    .data_13_V_read(layer4_out_13_V_dout),
    .data_14_V_read(layer4_out_14_V_dout),
    .ap_return_0(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_0),
    .ap_return_1(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_1),
    .ap_return_2(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_2),
    .ap_return_3(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_3),
    .ap_return_4(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_4),
    .ap_return_5(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_5),
    .ap_return_6(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_6),
    .ap_return_7(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_7),
    .ap_return_8(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_8),
    .ap_return_9(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_9),
    .ap_return_10(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_10),
    .ap_return_11(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_11),
    .ap_return_12(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_12),
    .ap_return_13(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_13),
    .ap_return_14(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_14)
);

Block_codeRepl320123320129_proc72 Block_codeRepl320123320129_proc72_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Block_codeRepl320123320129_proc72_U0_ap_start),
    .ap_done(Block_codeRepl320123320129_proc72_U0_ap_done),
    .ap_continue(Block_codeRepl320123320129_proc72_U0_ap_continue),
    .ap_idle(Block_codeRepl320123320129_proc72_U0_ap_idle),
    .ap_ready(Block_codeRepl320123320129_proc72_U0_ap_ready),
    .p_read(layer5_out_0_V_dout),
    .p_read1(layer5_out_1_V_dout),
    .p_read2(layer5_out_2_V_dout),
    .p_read3(layer5_out_3_V_dout),
    .p_read4(layer5_out_4_V_dout),
    .p_read5(layer5_out_5_V_dout),
    .p_read6(layer5_out_6_V_dout),
    .p_read7(layer5_out_7_V_dout),
    .p_read8(layer5_out_8_V_dout),
    .p_read9(layer5_out_9_V_dout),
    .p_read10(layer5_out_10_V_dout),
    .p_read11(layer5_out_11_V_dout),
    .p_read12(layer5_out_12_V_dout),
    .p_read13(layer5_out_13_V_dout),
    .p_read14(layer5_out_14_V_dout),
    .link_out_0_V_i(link_out_0_V_i),
    .link_out_0_V_o(Block_codeRepl320123320129_proc72_U0_link_out_0_V_o),
    .link_out_0_V_o_ap_vld(Block_codeRepl320123320129_proc72_U0_link_out_0_V_o_ap_vld)
);

fifo_w2520_d2_A Inputs_V_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl320123_proc_U0_ap_return),
    .if_full_n(Inputs_V_channel_full_n),
    .if_write(Block_codeRepl320123_proc_U0_ap_done),
    .if_dout(Inputs_V_channel_dout),
    .if_empty_n(Inputs_V_channel_empty_n),
    .if_read(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_ready)
);

fifo_w20_d2_A layer2_out_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_0),
    .if_full_n(layer2_out_0_V_full_n),
    .if_write(ap_channel_done_layer2_out_0_V),
    .if_dout(layer2_out_0_V_dout),
    .if_empty_n(layer2_out_0_V_empty_n),
    .if_read(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_ready)
);

fifo_w20_d2_A layer2_out_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_1),
    .if_full_n(layer2_out_1_V_full_n),
    .if_write(ap_channel_done_layer2_out_1_V),
    .if_dout(layer2_out_1_V_dout),
    .if_empty_n(layer2_out_1_V_empty_n),
    .if_read(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_ready)
);

fifo_w20_d2_A layer2_out_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_2),
    .if_full_n(layer2_out_2_V_full_n),
    .if_write(ap_channel_done_layer2_out_2_V),
    .if_dout(layer2_out_2_V_dout),
    .if_empty_n(layer2_out_2_V_empty_n),
    .if_read(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_ready)
);

fifo_w20_d2_A layer2_out_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_3),
    .if_full_n(layer2_out_3_V_full_n),
    .if_write(ap_channel_done_layer2_out_3_V),
    .if_dout(layer2_out_3_V_dout),
    .if_empty_n(layer2_out_3_V_empty_n),
    .if_read(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_ready)
);

fifo_w20_d2_A layer2_out_4_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_4),
    .if_full_n(layer2_out_4_V_full_n),
    .if_write(ap_channel_done_layer2_out_4_V),
    .if_dout(layer2_out_4_V_dout),
    .if_empty_n(layer2_out_4_V_empty_n),
    .if_read(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_ready)
);

fifo_w20_d2_A layer2_out_5_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_5),
    .if_full_n(layer2_out_5_V_full_n),
    .if_write(ap_channel_done_layer2_out_5_V),
    .if_dout(layer2_out_5_V_dout),
    .if_empty_n(layer2_out_5_V_empty_n),
    .if_read(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_ready)
);

fifo_w20_d2_A layer2_out_6_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_6),
    .if_full_n(layer2_out_6_V_full_n),
    .if_write(ap_channel_done_layer2_out_6_V),
    .if_dout(layer2_out_6_V_dout),
    .if_empty_n(layer2_out_6_V_empty_n),
    .if_read(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_ready)
);

fifo_w20_d2_A layer2_out_7_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_7),
    .if_full_n(layer2_out_7_V_full_n),
    .if_write(ap_channel_done_layer2_out_7_V),
    .if_dout(layer2_out_7_V_dout),
    .if_empty_n(layer2_out_7_V_empty_n),
    .if_read(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_ready)
);

fifo_w20_d2_A layer2_out_8_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_8),
    .if_full_n(layer2_out_8_V_full_n),
    .if_write(ap_channel_done_layer2_out_8_V),
    .if_dout(layer2_out_8_V_dout),
    .if_empty_n(layer2_out_8_V_empty_n),
    .if_read(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_ready)
);

fifo_w20_d2_A layer2_out_9_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_9),
    .if_full_n(layer2_out_9_V_full_n),
    .if_write(ap_channel_done_layer2_out_9_V),
    .if_dout(layer2_out_9_V_dout),
    .if_empty_n(layer2_out_9_V_empty_n),
    .if_read(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_ready)
);

fifo_w20_d2_A layer2_out_10_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_10),
    .if_full_n(layer2_out_10_V_full_n),
    .if_write(ap_channel_done_layer2_out_10_V),
    .if_dout(layer2_out_10_V_dout),
    .if_empty_n(layer2_out_10_V_empty_n),
    .if_read(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_ready)
);

fifo_w20_d2_A layer2_out_11_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_11),
    .if_full_n(layer2_out_11_V_full_n),
    .if_write(ap_channel_done_layer2_out_11_V),
    .if_dout(layer2_out_11_V_dout),
    .if_empty_n(layer2_out_11_V_empty_n),
    .if_read(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_ready)
);

fifo_w20_d2_A layer2_out_12_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_12),
    .if_full_n(layer2_out_12_V_full_n),
    .if_write(ap_channel_done_layer2_out_12_V),
    .if_dout(layer2_out_12_V_dout),
    .if_empty_n(layer2_out_12_V_empty_n),
    .if_read(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_ready)
);

fifo_w20_d2_A layer2_out_13_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_13),
    .if_full_n(layer2_out_13_V_full_n),
    .if_write(ap_channel_done_layer2_out_13_V),
    .if_dout(layer2_out_13_V_dout),
    .if_empty_n(layer2_out_13_V_empty_n),
    .if_read(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_ready)
);

fifo_w20_d2_A layer2_out_14_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_return_14),
    .if_full_n(layer2_out_14_V_full_n),
    .if_write(ap_channel_done_layer2_out_14_V),
    .if_dout(layer2_out_14_V_dout),
    .if_empty_n(layer2_out_14_V_empty_n),
    .if_read(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_ready)
);

fifo_w20_d2_A layer4_out_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_0),
    .if_full_n(layer4_out_0_V_full_n),
    .if_write(ap_channel_done_layer4_out_0_V),
    .if_dout(layer4_out_0_V_dout),
    .if_empty_n(layer4_out_0_V_empty_n),
    .if_read(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_ready)
);

fifo_w20_d2_A layer4_out_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_1),
    .if_full_n(layer4_out_1_V_full_n),
    .if_write(ap_channel_done_layer4_out_1_V),
    .if_dout(layer4_out_1_V_dout),
    .if_empty_n(layer4_out_1_V_empty_n),
    .if_read(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_ready)
);

fifo_w20_d2_A layer4_out_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_2),
    .if_full_n(layer4_out_2_V_full_n),
    .if_write(ap_channel_done_layer4_out_2_V),
    .if_dout(layer4_out_2_V_dout),
    .if_empty_n(layer4_out_2_V_empty_n),
    .if_read(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_ready)
);

fifo_w20_d2_A layer4_out_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_3),
    .if_full_n(layer4_out_3_V_full_n),
    .if_write(ap_channel_done_layer4_out_3_V),
    .if_dout(layer4_out_3_V_dout),
    .if_empty_n(layer4_out_3_V_empty_n),
    .if_read(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_ready)
);

fifo_w20_d2_A layer4_out_4_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_4),
    .if_full_n(layer4_out_4_V_full_n),
    .if_write(ap_channel_done_layer4_out_4_V),
    .if_dout(layer4_out_4_V_dout),
    .if_empty_n(layer4_out_4_V_empty_n),
    .if_read(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_ready)
);

fifo_w20_d2_A layer4_out_5_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_5),
    .if_full_n(layer4_out_5_V_full_n),
    .if_write(ap_channel_done_layer4_out_5_V),
    .if_dout(layer4_out_5_V_dout),
    .if_empty_n(layer4_out_5_V_empty_n),
    .if_read(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_ready)
);

fifo_w20_d2_A layer4_out_6_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_6),
    .if_full_n(layer4_out_6_V_full_n),
    .if_write(ap_channel_done_layer4_out_6_V),
    .if_dout(layer4_out_6_V_dout),
    .if_empty_n(layer4_out_6_V_empty_n),
    .if_read(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_ready)
);

fifo_w20_d2_A layer4_out_7_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_7),
    .if_full_n(layer4_out_7_V_full_n),
    .if_write(ap_channel_done_layer4_out_7_V),
    .if_dout(layer4_out_7_V_dout),
    .if_empty_n(layer4_out_7_V_empty_n),
    .if_read(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_ready)
);

fifo_w20_d2_A layer4_out_8_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_8),
    .if_full_n(layer4_out_8_V_full_n),
    .if_write(ap_channel_done_layer4_out_8_V),
    .if_dout(layer4_out_8_V_dout),
    .if_empty_n(layer4_out_8_V_empty_n),
    .if_read(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_ready)
);

fifo_w20_d2_A layer4_out_9_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_9),
    .if_full_n(layer4_out_9_V_full_n),
    .if_write(ap_channel_done_layer4_out_9_V),
    .if_dout(layer4_out_9_V_dout),
    .if_empty_n(layer4_out_9_V_empty_n),
    .if_read(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_ready)
);

fifo_w20_d2_A layer4_out_10_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_10),
    .if_full_n(layer4_out_10_V_full_n),
    .if_write(ap_channel_done_layer4_out_10_V),
    .if_dout(layer4_out_10_V_dout),
    .if_empty_n(layer4_out_10_V_empty_n),
    .if_read(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_ready)
);

fifo_w20_d2_A layer4_out_11_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_11),
    .if_full_n(layer4_out_11_V_full_n),
    .if_write(ap_channel_done_layer4_out_11_V),
    .if_dout(layer4_out_11_V_dout),
    .if_empty_n(layer4_out_11_V_empty_n),
    .if_read(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_ready)
);

fifo_w20_d2_A layer4_out_12_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_12),
    .if_full_n(layer4_out_12_V_full_n),
    .if_write(ap_channel_done_layer4_out_12_V),
    .if_dout(layer4_out_12_V_dout),
    .if_empty_n(layer4_out_12_V_empty_n),
    .if_read(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_ready)
);

fifo_w20_d2_A layer4_out_13_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_13),
    .if_full_n(layer4_out_13_V_full_n),
    .if_write(ap_channel_done_layer4_out_13_V),
    .if_dout(layer4_out_13_V_dout),
    .if_empty_n(layer4_out_13_V_empty_n),
    .if_read(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_ready)
);

fifo_w20_d2_A layer4_out_14_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_return_14),
    .if_full_n(layer4_out_14_V_full_n),
    .if_write(ap_channel_done_layer4_out_14_V),
    .if_dout(layer4_out_14_V_dout),
    .if_empty_n(layer4_out_14_V_empty_n),
    .if_read(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_ready)
);

fifo_w5_d2_A layer5_out_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_0),
    .if_full_n(layer5_out_0_V_full_n),
    .if_write(ap_channel_done_layer5_out_0_V),
    .if_dout(layer5_out_0_V_dout),
    .if_empty_n(layer5_out_0_V_empty_n),
    .if_read(Block_codeRepl320123320129_proc72_U0_ap_ready)
);

fifo_w5_d2_A layer5_out_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_1),
    .if_full_n(layer5_out_1_V_full_n),
    .if_write(ap_channel_done_layer5_out_1_V),
    .if_dout(layer5_out_1_V_dout),
    .if_empty_n(layer5_out_1_V_empty_n),
    .if_read(Block_codeRepl320123320129_proc72_U0_ap_ready)
);

fifo_w5_d2_A layer5_out_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_2),
    .if_full_n(layer5_out_2_V_full_n),
    .if_write(ap_channel_done_layer5_out_2_V),
    .if_dout(layer5_out_2_V_dout),
    .if_empty_n(layer5_out_2_V_empty_n),
    .if_read(Block_codeRepl320123320129_proc72_U0_ap_ready)
);

fifo_w5_d2_A layer5_out_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_3),
    .if_full_n(layer5_out_3_V_full_n),
    .if_write(ap_channel_done_layer5_out_3_V),
    .if_dout(layer5_out_3_V_dout),
    .if_empty_n(layer5_out_3_V_empty_n),
    .if_read(Block_codeRepl320123320129_proc72_U0_ap_ready)
);

fifo_w5_d2_A layer5_out_4_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_4),
    .if_full_n(layer5_out_4_V_full_n),
    .if_write(ap_channel_done_layer5_out_4_V),
    .if_dout(layer5_out_4_V_dout),
    .if_empty_n(layer5_out_4_V_empty_n),
    .if_read(Block_codeRepl320123320129_proc72_U0_ap_ready)
);

fifo_w5_d2_A layer5_out_5_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_5),
    .if_full_n(layer5_out_5_V_full_n),
    .if_write(ap_channel_done_layer5_out_5_V),
    .if_dout(layer5_out_5_V_dout),
    .if_empty_n(layer5_out_5_V_empty_n),
    .if_read(Block_codeRepl320123320129_proc72_U0_ap_ready)
);

fifo_w5_d2_A layer5_out_6_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_6),
    .if_full_n(layer5_out_6_V_full_n),
    .if_write(ap_channel_done_layer5_out_6_V),
    .if_dout(layer5_out_6_V_dout),
    .if_empty_n(layer5_out_6_V_empty_n),
    .if_read(Block_codeRepl320123320129_proc72_U0_ap_ready)
);

fifo_w5_d2_A layer5_out_7_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_7),
    .if_full_n(layer5_out_7_V_full_n),
    .if_write(ap_channel_done_layer5_out_7_V),
    .if_dout(layer5_out_7_V_dout),
    .if_empty_n(layer5_out_7_V_empty_n),
    .if_read(Block_codeRepl320123320129_proc72_U0_ap_ready)
);

fifo_w5_d2_A layer5_out_8_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_8),
    .if_full_n(layer5_out_8_V_full_n),
    .if_write(ap_channel_done_layer5_out_8_V),
    .if_dout(layer5_out_8_V_dout),
    .if_empty_n(layer5_out_8_V_empty_n),
    .if_read(Block_codeRepl320123320129_proc72_U0_ap_ready)
);

fifo_w5_d2_A layer5_out_9_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_9),
    .if_full_n(layer5_out_9_V_full_n),
    .if_write(ap_channel_done_layer5_out_9_V),
    .if_dout(layer5_out_9_V_dout),
    .if_empty_n(layer5_out_9_V_empty_n),
    .if_read(Block_codeRepl320123320129_proc72_U0_ap_ready)
);

fifo_w5_d2_A layer5_out_10_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_10),
    .if_full_n(layer5_out_10_V_full_n),
    .if_write(ap_channel_done_layer5_out_10_V),
    .if_dout(layer5_out_10_V_dout),
    .if_empty_n(layer5_out_10_V_empty_n),
    .if_read(Block_codeRepl320123320129_proc72_U0_ap_ready)
);

fifo_w5_d2_A layer5_out_11_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_11),
    .if_full_n(layer5_out_11_V_full_n),
    .if_write(ap_channel_done_layer5_out_11_V),
    .if_dout(layer5_out_11_V_dout),
    .if_empty_n(layer5_out_11_V_empty_n),
    .if_read(Block_codeRepl320123320129_proc72_U0_ap_ready)
);

fifo_w5_d2_A layer5_out_12_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_12),
    .if_full_n(layer5_out_12_V_full_n),
    .if_write(ap_channel_done_layer5_out_12_V),
    .if_dout(layer5_out_12_V_dout),
    .if_empty_n(layer5_out_12_V_empty_n),
    .if_read(Block_codeRepl320123320129_proc72_U0_ap_ready)
);

fifo_w5_d2_A layer5_out_13_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_13),
    .if_full_n(layer5_out_13_V_full_n),
    .if_write(ap_channel_done_layer5_out_13_V),
    .if_dout(layer5_out_13_V_dout),
    .if_empty_n(layer5_out_13_V_empty_n),
    .if_read(Block_codeRepl320123320129_proc72_U0_ap_ready)
);

fifo_w5_d2_A layer5_out_14_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_return_14),
    .if_full_n(layer5_out_14_V_full_n),
    .if_write(ap_channel_done_layer5_out_14_V),
    .if_dout(layer5_out_14_V_dout),
    .if_empty_n(layer5_out_14_V_empty_n),
    .if_read(Block_codeRepl320123320129_proc72_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_Block_codeRepl320123320129_proc72_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_codeRepl320123320129_proc72_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_codeRepl320123320129_proc72_U0_ap_ready <= ap_sync_Block_codeRepl320123320129_proc72_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_Block_codeRepl320123_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_codeRepl320123_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_codeRepl320123_proc_U0_ap_ready <= ap_sync_Block_codeRepl320123_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer2_out_0_V <= 1'b0;
    end else begin
        if (((dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer2_out_0_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer2_out_0_V <= ap_sync_channel_write_layer2_out_0_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer2_out_10_V <= 1'b0;
    end else begin
        if (((dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer2_out_10_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer2_out_10_V <= ap_sync_channel_write_layer2_out_10_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer2_out_11_V <= 1'b0;
    end else begin
        if (((dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer2_out_11_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer2_out_11_V <= ap_sync_channel_write_layer2_out_11_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer2_out_12_V <= 1'b0;
    end else begin
        if (((dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer2_out_12_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer2_out_12_V <= ap_sync_channel_write_layer2_out_12_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer2_out_13_V <= 1'b0;
    end else begin
        if (((dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer2_out_13_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer2_out_13_V <= ap_sync_channel_write_layer2_out_13_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer2_out_14_V <= 1'b0;
    end else begin
        if (((dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer2_out_14_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer2_out_14_V <= ap_sync_channel_write_layer2_out_14_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer2_out_1_V <= 1'b0;
    end else begin
        if (((dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer2_out_1_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer2_out_1_V <= ap_sync_channel_write_layer2_out_1_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer2_out_2_V <= 1'b0;
    end else begin
        if (((dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer2_out_2_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer2_out_2_V <= ap_sync_channel_write_layer2_out_2_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer2_out_3_V <= 1'b0;
    end else begin
        if (((dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer2_out_3_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer2_out_3_V <= ap_sync_channel_write_layer2_out_3_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer2_out_4_V <= 1'b0;
    end else begin
        if (((dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer2_out_4_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer2_out_4_V <= ap_sync_channel_write_layer2_out_4_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer2_out_5_V <= 1'b0;
    end else begin
        if (((dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer2_out_5_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer2_out_5_V <= ap_sync_channel_write_layer2_out_5_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer2_out_6_V <= 1'b0;
    end else begin
        if (((dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer2_out_6_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer2_out_6_V <= ap_sync_channel_write_layer2_out_6_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer2_out_7_V <= 1'b0;
    end else begin
        if (((dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer2_out_7_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer2_out_7_V <= ap_sync_channel_write_layer2_out_7_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer2_out_8_V <= 1'b0;
    end else begin
        if (((dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer2_out_8_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer2_out_8_V <= ap_sync_channel_write_layer2_out_8_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer2_out_9_V <= 1'b0;
    end else begin
        if (((dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer2_out_9_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer2_out_9_V <= ap_sync_channel_write_layer2_out_9_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer4_out_0_V <= 1'b0;
    end else begin
        if (((normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer4_out_0_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer4_out_0_V <= ap_sync_channel_write_layer4_out_0_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer4_out_10_V <= 1'b0;
    end else begin
        if (((normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer4_out_10_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer4_out_10_V <= ap_sync_channel_write_layer4_out_10_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer4_out_11_V <= 1'b0;
    end else begin
        if (((normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer4_out_11_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer4_out_11_V <= ap_sync_channel_write_layer4_out_11_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer4_out_12_V <= 1'b0;
    end else begin
        if (((normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer4_out_12_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer4_out_12_V <= ap_sync_channel_write_layer4_out_12_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer4_out_13_V <= 1'b0;
    end else begin
        if (((normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer4_out_13_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer4_out_13_V <= ap_sync_channel_write_layer4_out_13_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer4_out_14_V <= 1'b0;
    end else begin
        if (((normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer4_out_14_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer4_out_14_V <= ap_sync_channel_write_layer4_out_14_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer4_out_1_V <= 1'b0;
    end else begin
        if (((normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer4_out_1_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer4_out_1_V <= ap_sync_channel_write_layer4_out_1_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer4_out_2_V <= 1'b0;
    end else begin
        if (((normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer4_out_2_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer4_out_2_V <= ap_sync_channel_write_layer4_out_2_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer4_out_3_V <= 1'b0;
    end else begin
        if (((normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer4_out_3_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer4_out_3_V <= ap_sync_channel_write_layer4_out_3_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer4_out_4_V <= 1'b0;
    end else begin
        if (((normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer4_out_4_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer4_out_4_V <= ap_sync_channel_write_layer4_out_4_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer4_out_5_V <= 1'b0;
    end else begin
        if (((normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer4_out_5_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer4_out_5_V <= ap_sync_channel_write_layer4_out_5_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer4_out_6_V <= 1'b0;
    end else begin
        if (((normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer4_out_6_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer4_out_6_V <= ap_sync_channel_write_layer4_out_6_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer4_out_7_V <= 1'b0;
    end else begin
        if (((normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer4_out_7_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer4_out_7_V <= ap_sync_channel_write_layer4_out_7_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer4_out_8_V <= 1'b0;
    end else begin
        if (((normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer4_out_8_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer4_out_8_V <= ap_sync_channel_write_layer4_out_8_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer4_out_9_V <= 1'b0;
    end else begin
        if (((normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer4_out_9_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer4_out_9_V <= ap_sync_channel_write_layer4_out_9_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer5_out_0_V <= 1'b0;
    end else begin
        if (((relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer5_out_0_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer5_out_0_V <= ap_sync_channel_write_layer5_out_0_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer5_out_10_V <= 1'b0;
    end else begin
        if (((relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer5_out_10_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer5_out_10_V <= ap_sync_channel_write_layer5_out_10_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer5_out_11_V <= 1'b0;
    end else begin
        if (((relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer5_out_11_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer5_out_11_V <= ap_sync_channel_write_layer5_out_11_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer5_out_12_V <= 1'b0;
    end else begin
        if (((relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer5_out_12_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer5_out_12_V <= ap_sync_channel_write_layer5_out_12_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer5_out_13_V <= 1'b0;
    end else begin
        if (((relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer5_out_13_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer5_out_13_V <= ap_sync_channel_write_layer5_out_13_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer5_out_14_V <= 1'b0;
    end else begin
        if (((relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer5_out_14_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer5_out_14_V <= ap_sync_channel_write_layer5_out_14_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer5_out_1_V <= 1'b0;
    end else begin
        if (((relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer5_out_1_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer5_out_1_V <= ap_sync_channel_write_layer5_out_1_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer5_out_2_V <= 1'b0;
    end else begin
        if (((relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer5_out_2_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer5_out_2_V <= ap_sync_channel_write_layer5_out_2_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer5_out_3_V <= 1'b0;
    end else begin
        if (((relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer5_out_3_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer5_out_3_V <= ap_sync_channel_write_layer5_out_3_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer5_out_4_V <= 1'b0;
    end else begin
        if (((relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer5_out_4_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer5_out_4_V <= ap_sync_channel_write_layer5_out_4_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer5_out_5_V <= 1'b0;
    end else begin
        if (((relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer5_out_5_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer5_out_5_V <= ap_sync_channel_write_layer5_out_5_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer5_out_6_V <= 1'b0;
    end else begin
        if (((relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer5_out_6_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer5_out_6_V <= ap_sync_channel_write_layer5_out_6_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer5_out_7_V <= 1'b0;
    end else begin
        if (((relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer5_out_7_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer5_out_7_V <= ap_sync_channel_write_layer5_out_7_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer5_out_8_V <= 1'b0;
    end else begin
        if (((relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer5_out_8_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer5_out_8_V <= ap_sync_channel_write_layer5_out_8_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_layer5_out_9_V <= 1'b0;
    end else begin
        if (((relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_layer5_out_9_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_layer5_out_9_V <= ap_sync_channel_write_layer5_out_9_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (1'b0 == Block_codeRepl320123320129_proc72_U0_ap_ready))) begin
        Block_codeRepl320123320129_proc72_U0_ap_ready_count <= (Block_codeRepl320123320129_proc72_U0_ap_ready_count - 2'd1);
    end else if (((1'b1 == Block_codeRepl320123320129_proc72_U0_ap_ready) & (ap_sync_ready == 1'b0))) begin
        Block_codeRepl320123320129_proc72_U0_ap_ready_count <= (Block_codeRepl320123320129_proc72_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (1'b0 == Block_codeRepl320123_proc_U0_ap_ready))) begin
        Block_codeRepl320123_proc_U0_ap_ready_count <= (Block_codeRepl320123_proc_U0_ap_ready_count - 2'd1);
    end else if (((1'b1 == Block_codeRepl320123_proc_U0_ap_ready) & (ap_sync_ready == 1'b0))) begin
        Block_codeRepl320123_proc_U0_ap_ready_count <= (Block_codeRepl320123_proc_U0_ap_ready_count + 2'd1);
    end
end

assign Block_codeRepl320123320129_proc72_U0_ap_continue = 1'b1;

assign Block_codeRepl320123320129_proc72_U0_ap_start = (layer5_out_9_V_empty_n & layer5_out_8_V_empty_n & layer5_out_7_V_empty_n & layer5_out_6_V_empty_n & layer5_out_5_V_empty_n & layer5_out_4_V_empty_n & layer5_out_3_V_empty_n & layer5_out_2_V_empty_n & layer5_out_1_V_empty_n & layer5_out_14_V_empty_n & layer5_out_13_V_empty_n & layer5_out_12_V_empty_n & layer5_out_11_V_empty_n & layer5_out_10_V_empty_n & layer5_out_0_V_empty_n & (ap_sync_reg_Block_codeRepl320123320129_proc72_U0_ap_ready ^ 1'b1) & ap_start);

assign Block_codeRepl320123320129_proc72_U0_start_full_n = 1'b1;

assign Block_codeRepl320123320129_proc72_U0_start_write = 1'b0;

assign Block_codeRepl320123_proc_U0_ap_continue = Inputs_V_channel_full_n;

assign Block_codeRepl320123_proc_U0_ap_start = ((ap_sync_reg_Block_codeRepl320123_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign Block_codeRepl320123_proc_U0_start_full_n = 1'b1;

assign Block_codeRepl320123_proc_U0_start_write = 1'b0;

assign ap_channel_done_Inputs_V_channel = Block_codeRepl320123_proc_U0_ap_done;

assign ap_channel_done_layer2_out_0_V = ((ap_sync_reg_channel_write_layer2_out_0_V ^ 1'b1) & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done);

assign ap_channel_done_layer2_out_10_V = ((ap_sync_reg_channel_write_layer2_out_10_V ^ 1'b1) & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done);

assign ap_channel_done_layer2_out_11_V = ((ap_sync_reg_channel_write_layer2_out_11_V ^ 1'b1) & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done);

assign ap_channel_done_layer2_out_12_V = ((ap_sync_reg_channel_write_layer2_out_12_V ^ 1'b1) & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done);

assign ap_channel_done_layer2_out_13_V = ((ap_sync_reg_channel_write_layer2_out_13_V ^ 1'b1) & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done);

assign ap_channel_done_layer2_out_14_V = ((ap_sync_reg_channel_write_layer2_out_14_V ^ 1'b1) & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done);

assign ap_channel_done_layer2_out_1_V = ((ap_sync_reg_channel_write_layer2_out_1_V ^ 1'b1) & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done);

assign ap_channel_done_layer2_out_2_V = ((ap_sync_reg_channel_write_layer2_out_2_V ^ 1'b1) & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done);

assign ap_channel_done_layer2_out_3_V = ((ap_sync_reg_channel_write_layer2_out_3_V ^ 1'b1) & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done);

assign ap_channel_done_layer2_out_4_V = ((ap_sync_reg_channel_write_layer2_out_4_V ^ 1'b1) & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done);

assign ap_channel_done_layer2_out_5_V = ((ap_sync_reg_channel_write_layer2_out_5_V ^ 1'b1) & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done);

assign ap_channel_done_layer2_out_6_V = ((ap_sync_reg_channel_write_layer2_out_6_V ^ 1'b1) & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done);

assign ap_channel_done_layer2_out_7_V = ((ap_sync_reg_channel_write_layer2_out_7_V ^ 1'b1) & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done);

assign ap_channel_done_layer2_out_8_V = ((ap_sync_reg_channel_write_layer2_out_8_V ^ 1'b1) & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done);

assign ap_channel_done_layer2_out_9_V = ((ap_sync_reg_channel_write_layer2_out_9_V ^ 1'b1) & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_done);

assign ap_channel_done_layer4_out_0_V = (normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & (ap_sync_reg_channel_write_layer4_out_0_V ^ 1'b1));

assign ap_channel_done_layer4_out_10_V = (normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & (ap_sync_reg_channel_write_layer4_out_10_V ^ 1'b1));

assign ap_channel_done_layer4_out_11_V = (normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & (ap_sync_reg_channel_write_layer4_out_11_V ^ 1'b1));

assign ap_channel_done_layer4_out_12_V = (normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & (ap_sync_reg_channel_write_layer4_out_12_V ^ 1'b1));

assign ap_channel_done_layer4_out_13_V = (normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & (ap_sync_reg_channel_write_layer4_out_13_V ^ 1'b1));

assign ap_channel_done_layer4_out_14_V = (normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & (ap_sync_reg_channel_write_layer4_out_14_V ^ 1'b1));

assign ap_channel_done_layer4_out_1_V = (normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & (ap_sync_reg_channel_write_layer4_out_1_V ^ 1'b1));

assign ap_channel_done_layer4_out_2_V = (normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & (ap_sync_reg_channel_write_layer4_out_2_V ^ 1'b1));

assign ap_channel_done_layer4_out_3_V = (normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & (ap_sync_reg_channel_write_layer4_out_3_V ^ 1'b1));

assign ap_channel_done_layer4_out_4_V = (normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & (ap_sync_reg_channel_write_layer4_out_4_V ^ 1'b1));

assign ap_channel_done_layer4_out_5_V = (normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & (ap_sync_reg_channel_write_layer4_out_5_V ^ 1'b1));

assign ap_channel_done_layer4_out_6_V = (normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & (ap_sync_reg_channel_write_layer4_out_6_V ^ 1'b1));

assign ap_channel_done_layer4_out_7_V = (normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & (ap_sync_reg_channel_write_layer4_out_7_V ^ 1'b1));

assign ap_channel_done_layer4_out_8_V = (normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & (ap_sync_reg_channel_write_layer4_out_8_V ^ 1'b1));

assign ap_channel_done_layer4_out_9_V = (normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_done & (ap_sync_reg_channel_write_layer4_out_9_V ^ 1'b1));

assign ap_channel_done_layer5_out_0_V = (relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & (ap_sync_reg_channel_write_layer5_out_0_V ^ 1'b1));

assign ap_channel_done_layer5_out_10_V = (relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & (ap_sync_reg_channel_write_layer5_out_10_V ^ 1'b1));

assign ap_channel_done_layer5_out_11_V = (relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & (ap_sync_reg_channel_write_layer5_out_11_V ^ 1'b1));

assign ap_channel_done_layer5_out_12_V = (relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & (ap_sync_reg_channel_write_layer5_out_12_V ^ 1'b1));

assign ap_channel_done_layer5_out_13_V = (relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & (ap_sync_reg_channel_write_layer5_out_13_V ^ 1'b1));

assign ap_channel_done_layer5_out_14_V = (relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & (ap_sync_reg_channel_write_layer5_out_14_V ^ 1'b1));

assign ap_channel_done_layer5_out_1_V = (relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & (ap_sync_reg_channel_write_layer5_out_1_V ^ 1'b1));

assign ap_channel_done_layer5_out_2_V = (relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & (ap_sync_reg_channel_write_layer5_out_2_V ^ 1'b1));

assign ap_channel_done_layer5_out_3_V = (relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & (ap_sync_reg_channel_write_layer5_out_3_V ^ 1'b1));

assign ap_channel_done_layer5_out_4_V = (relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & (ap_sync_reg_channel_write_layer5_out_4_V ^ 1'b1));

assign ap_channel_done_layer5_out_5_V = (relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & (ap_sync_reg_channel_write_layer5_out_5_V ^ 1'b1));

assign ap_channel_done_layer5_out_6_V = (relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & (ap_sync_reg_channel_write_layer5_out_6_V ^ 1'b1));

assign ap_channel_done_layer5_out_7_V = (relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & (ap_sync_reg_channel_write_layer5_out_7_V ^ 1'b1));

assign ap_channel_done_layer5_out_8_V = (relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & (ap_sync_reg_channel_write_layer5_out_8_V ^ 1'b1));

assign ap_channel_done_layer5_out_9_V = (relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_done & (ap_sync_reg_channel_write_layer5_out_9_V ^ 1'b1));

assign ap_done = Block_codeRepl320123320129_proc72_U0_ap_done;

assign ap_idle = (relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_idle & normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_idle & (layer5_out_6_V_empty_n ^ 1'b1) & (layer5_out_5_V_empty_n ^ 1'b1) & (layer5_out_4_V_empty_n ^ 1'b1) & (layer5_out_3_V_empty_n ^ 1'b1) & (layer5_out_2_V_empty_n ^ 1'b1) & (layer5_out_1_V_empty_n ^ 1'b1) & (layer5_out_0_V_empty_n ^ 1'b1) & (layer4_out_14_V_empty_n ^ 1'b1) & (layer4_out_13_V_empty_n ^ 1'b1) & (layer4_out_12_V_empty_n ^ 1'b1) & (layer4_out_11_V_empty_n ^ 1'b1) & (layer4_out_10_V_empty_n ^ 1'b1) & (layer4_out_9_V_empty_n ^ 1'b1) & (layer4_out_8_V_empty_n ^ 1'b1) & (layer4_out_7_V_empty_n ^ 1'b1) & (layer4_out_6_V_empty_n ^ 1'b1) & (layer4_out_5_V_empty_n ^ 1'b1) & (layer4_out_4_V_empty_n ^ 1'b1) & (layer4_out_3_V_empty_n ^ 1'b1) & (layer4_out_2_V_empty_n ^ 1'b1) & (layer4_out_1_V_empty_n ^ 1'b1) & (layer4_out_0_V_empty_n ^ 1'b1) & (layer2_out_14_V_empty_n ^ 1'b1) & (layer2_out_13_V_empty_n ^ 1'b1) & (layer2_out_12_V_empty_n ^ 1'b1) & (layer2_out_11_V_empty_n ^ 1'b1) & (layer2_out_10_V_empty_n ^ 1'b1) & (layer2_out_9_V_empty_n ^ 1'b1) & (layer2_out_8_V_empty_n ^ 1'b1) & (layer2_out_7_V_empty_n ^ 1'b1) & (layer2_out_6_V_empty_n ^ 1'b1) & (layer2_out_5_V_empty_n ^ 1'b1) & (layer2_out_4_V_empty_n ^ 1'b1) & (layer2_out_3_V_empty_n ^ 1'b1) & (layer2_out_2_V_empty_n ^ 1'b1) & (layer2_out_1_V_empty_n ^ 1'b1) & (layer2_out_0_V_empty_n ^ 1'b1) & (1'b1 ^ Inputs_V_channel_empty_n) & (layer5_out_14_V_empty_n ^ 1'b1) & (layer5_out_13_V_empty_n ^ 1'b1) & (layer5_out_12_V_empty_n ^ 1'b1) & (layer5_out_11_V_empty_n ^ 1'b1) & (layer5_out_10_V_empty_n ^ 1'b1) & (layer5_out_9_V_empty_n ^ 1'b1) & (layer5_out_8_V_empty_n ^ 1'b1) & (layer5_out_7_V_empty_n ^ 1'b1) & dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_idle & Block_codeRepl320123_proc_U0_ap_idle & Block_codeRepl320123320129_proc72_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_Block_codeRepl320123320129_proc72_U0_ap_ready = (ap_sync_reg_Block_codeRepl320123320129_proc72_U0_ap_ready | Block_codeRepl320123320129_proc72_U0_ap_ready);

assign ap_sync_Block_codeRepl320123_proc_U0_ap_ready = (ap_sync_reg_Block_codeRepl320123_proc_U0_ap_ready | Block_codeRepl320123_proc_U0_ap_ready);

assign ap_sync_channel_write_layer2_out_0_V = ((layer2_out_0_V_full_n & ap_channel_done_layer2_out_0_V) | ap_sync_reg_channel_write_layer2_out_0_V);

assign ap_sync_channel_write_layer2_out_10_V = ((layer2_out_10_V_full_n & ap_channel_done_layer2_out_10_V) | ap_sync_reg_channel_write_layer2_out_10_V);

assign ap_sync_channel_write_layer2_out_11_V = ((layer2_out_11_V_full_n & ap_channel_done_layer2_out_11_V) | ap_sync_reg_channel_write_layer2_out_11_V);

assign ap_sync_channel_write_layer2_out_12_V = ((layer2_out_12_V_full_n & ap_channel_done_layer2_out_12_V) | ap_sync_reg_channel_write_layer2_out_12_V);

assign ap_sync_channel_write_layer2_out_13_V = ((layer2_out_13_V_full_n & ap_channel_done_layer2_out_13_V) | ap_sync_reg_channel_write_layer2_out_13_V);

assign ap_sync_channel_write_layer2_out_14_V = ((layer2_out_14_V_full_n & ap_channel_done_layer2_out_14_V) | ap_sync_reg_channel_write_layer2_out_14_V);

assign ap_sync_channel_write_layer2_out_1_V = ((layer2_out_1_V_full_n & ap_channel_done_layer2_out_1_V) | ap_sync_reg_channel_write_layer2_out_1_V);

assign ap_sync_channel_write_layer2_out_2_V = ((layer2_out_2_V_full_n & ap_channel_done_layer2_out_2_V) | ap_sync_reg_channel_write_layer2_out_2_V);

assign ap_sync_channel_write_layer2_out_3_V = ((layer2_out_3_V_full_n & ap_channel_done_layer2_out_3_V) | ap_sync_reg_channel_write_layer2_out_3_V);

assign ap_sync_channel_write_layer2_out_4_V = ((layer2_out_4_V_full_n & ap_channel_done_layer2_out_4_V) | ap_sync_reg_channel_write_layer2_out_4_V);

assign ap_sync_channel_write_layer2_out_5_V = ((layer2_out_5_V_full_n & ap_channel_done_layer2_out_5_V) | ap_sync_reg_channel_write_layer2_out_5_V);

assign ap_sync_channel_write_layer2_out_6_V = ((layer2_out_6_V_full_n & ap_channel_done_layer2_out_6_V) | ap_sync_reg_channel_write_layer2_out_6_V);

assign ap_sync_channel_write_layer2_out_7_V = ((layer2_out_7_V_full_n & ap_channel_done_layer2_out_7_V) | ap_sync_reg_channel_write_layer2_out_7_V);

assign ap_sync_channel_write_layer2_out_8_V = ((layer2_out_8_V_full_n & ap_channel_done_layer2_out_8_V) | ap_sync_reg_channel_write_layer2_out_8_V);

assign ap_sync_channel_write_layer2_out_9_V = ((layer2_out_9_V_full_n & ap_channel_done_layer2_out_9_V) | ap_sync_reg_channel_write_layer2_out_9_V);

assign ap_sync_channel_write_layer4_out_0_V = ((layer4_out_0_V_full_n & ap_channel_done_layer4_out_0_V) | ap_sync_reg_channel_write_layer4_out_0_V);

assign ap_sync_channel_write_layer4_out_10_V = ((layer4_out_10_V_full_n & ap_channel_done_layer4_out_10_V) | ap_sync_reg_channel_write_layer4_out_10_V);

assign ap_sync_channel_write_layer4_out_11_V = ((layer4_out_11_V_full_n & ap_channel_done_layer4_out_11_V) | ap_sync_reg_channel_write_layer4_out_11_V);

assign ap_sync_channel_write_layer4_out_12_V = ((layer4_out_12_V_full_n & ap_channel_done_layer4_out_12_V) | ap_sync_reg_channel_write_layer4_out_12_V);

assign ap_sync_channel_write_layer4_out_13_V = ((layer4_out_13_V_full_n & ap_channel_done_layer4_out_13_V) | ap_sync_reg_channel_write_layer4_out_13_V);

assign ap_sync_channel_write_layer4_out_14_V = ((layer4_out_14_V_full_n & ap_channel_done_layer4_out_14_V) | ap_sync_reg_channel_write_layer4_out_14_V);

assign ap_sync_channel_write_layer4_out_1_V = ((layer4_out_1_V_full_n & ap_channel_done_layer4_out_1_V) | ap_sync_reg_channel_write_layer4_out_1_V);

assign ap_sync_channel_write_layer4_out_2_V = ((layer4_out_2_V_full_n & ap_channel_done_layer4_out_2_V) | ap_sync_reg_channel_write_layer4_out_2_V);

assign ap_sync_channel_write_layer4_out_3_V = ((layer4_out_3_V_full_n & ap_channel_done_layer4_out_3_V) | ap_sync_reg_channel_write_layer4_out_3_V);

assign ap_sync_channel_write_layer4_out_4_V = ((layer4_out_4_V_full_n & ap_channel_done_layer4_out_4_V) | ap_sync_reg_channel_write_layer4_out_4_V);

assign ap_sync_channel_write_layer4_out_5_V = ((layer4_out_5_V_full_n & ap_channel_done_layer4_out_5_V) | ap_sync_reg_channel_write_layer4_out_5_V);

assign ap_sync_channel_write_layer4_out_6_V = ((layer4_out_6_V_full_n & ap_channel_done_layer4_out_6_V) | ap_sync_reg_channel_write_layer4_out_6_V);

assign ap_sync_channel_write_layer4_out_7_V = ((layer4_out_7_V_full_n & ap_channel_done_layer4_out_7_V) | ap_sync_reg_channel_write_layer4_out_7_V);

assign ap_sync_channel_write_layer4_out_8_V = ((layer4_out_8_V_full_n & ap_channel_done_layer4_out_8_V) | ap_sync_reg_channel_write_layer4_out_8_V);

assign ap_sync_channel_write_layer4_out_9_V = ((layer4_out_9_V_full_n & ap_channel_done_layer4_out_9_V) | ap_sync_reg_channel_write_layer4_out_9_V);

assign ap_sync_channel_write_layer5_out_0_V = ((layer5_out_0_V_full_n & ap_channel_done_layer5_out_0_V) | ap_sync_reg_channel_write_layer5_out_0_V);

assign ap_sync_channel_write_layer5_out_10_V = ((layer5_out_10_V_full_n & ap_channel_done_layer5_out_10_V) | ap_sync_reg_channel_write_layer5_out_10_V);

assign ap_sync_channel_write_layer5_out_11_V = ((layer5_out_11_V_full_n & ap_channel_done_layer5_out_11_V) | ap_sync_reg_channel_write_layer5_out_11_V);

assign ap_sync_channel_write_layer5_out_12_V = ((layer5_out_12_V_full_n & ap_channel_done_layer5_out_12_V) | ap_sync_reg_channel_write_layer5_out_12_V);

assign ap_sync_channel_write_layer5_out_13_V = ((layer5_out_13_V_full_n & ap_channel_done_layer5_out_13_V) | ap_sync_reg_channel_write_layer5_out_13_V);

assign ap_sync_channel_write_layer5_out_14_V = ((layer5_out_14_V_full_n & ap_channel_done_layer5_out_14_V) | ap_sync_reg_channel_write_layer5_out_14_V);

assign ap_sync_channel_write_layer5_out_1_V = ((layer5_out_1_V_full_n & ap_channel_done_layer5_out_1_V) | ap_sync_reg_channel_write_layer5_out_1_V);

assign ap_sync_channel_write_layer5_out_2_V = ((layer5_out_2_V_full_n & ap_channel_done_layer5_out_2_V) | ap_sync_reg_channel_write_layer5_out_2_V);

assign ap_sync_channel_write_layer5_out_3_V = ((layer5_out_3_V_full_n & ap_channel_done_layer5_out_3_V) | ap_sync_reg_channel_write_layer5_out_3_V);

assign ap_sync_channel_write_layer5_out_4_V = ((layer5_out_4_V_full_n & ap_channel_done_layer5_out_4_V) | ap_sync_reg_channel_write_layer5_out_4_V);

assign ap_sync_channel_write_layer5_out_5_V = ((layer5_out_5_V_full_n & ap_channel_done_layer5_out_5_V) | ap_sync_reg_channel_write_layer5_out_5_V);

assign ap_sync_channel_write_layer5_out_6_V = ((layer5_out_6_V_full_n & ap_channel_done_layer5_out_6_V) | ap_sync_reg_channel_write_layer5_out_6_V);

assign ap_sync_channel_write_layer5_out_7_V = ((layer5_out_7_V_full_n & ap_channel_done_layer5_out_7_V) | ap_sync_reg_channel_write_layer5_out_7_V);

assign ap_sync_channel_write_layer5_out_8_V = ((layer5_out_8_V_full_n & ap_channel_done_layer5_out_8_V) | ap_sync_reg_channel_write_layer5_out_8_V);

assign ap_sync_channel_write_layer5_out_9_V = ((layer5_out_9_V_full_n & ap_channel_done_layer5_out_9_V) | ap_sync_reg_channel_write_layer5_out_9_V);

assign ap_sync_continue = 1'b1;

assign ap_sync_done = Block_codeRepl320123320129_proc72_U0_ap_done;

assign ap_sync_ready = (ap_sync_Block_codeRepl320123_proc_U0_ap_ready & ap_sync_Block_codeRepl320123320129_proc72_U0_ap_ready);

assign dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_continue = (ap_sync_channel_write_layer2_out_9_V & ap_sync_channel_write_layer2_out_8_V & ap_sync_channel_write_layer2_out_7_V & ap_sync_channel_write_layer2_out_6_V & ap_sync_channel_write_layer2_out_5_V & ap_sync_channel_write_layer2_out_4_V & ap_sync_channel_write_layer2_out_3_V & ap_sync_channel_write_layer2_out_2_V & ap_sync_channel_write_layer2_out_1_V & ap_sync_channel_write_layer2_out_14_V & ap_sync_channel_write_layer2_out_13_V & ap_sync_channel_write_layer2_out_12_V & ap_sync_channel_write_layer2_out_11_V & ap_sync_channel_write_layer2_out_10_V & ap_sync_channel_write_layer2_out_0_V);

assign dense_resource_ap_ufixed_ap_fixed_config2_U0_ap_start = Inputs_V_channel_empty_n;

assign dense_resource_ap_ufixed_ap_fixed_config2_U0_start_full_n = 1'b1;

assign dense_resource_ap_ufixed_ap_fixed_config2_U0_start_write = 1'b0;

assign link_out_0_V_o = Block_codeRepl320123320129_proc72_U0_link_out_0_V_o;

assign link_out_0_V_o_ap_vld = Block_codeRepl320123320129_proc72_U0_link_out_0_V_o_ap_vld;

assign normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_continue = (ap_sync_channel_write_layer4_out_9_V & ap_sync_channel_write_layer4_out_8_V & ap_sync_channel_write_layer4_out_7_V & ap_sync_channel_write_layer4_out_6_V & ap_sync_channel_write_layer4_out_5_V & ap_sync_channel_write_layer4_out_4_V & ap_sync_channel_write_layer4_out_3_V & ap_sync_channel_write_layer4_out_2_V & ap_sync_channel_write_layer4_out_1_V & ap_sync_channel_write_layer4_out_14_V & ap_sync_channel_write_layer4_out_13_V & ap_sync_channel_write_layer4_out_12_V & ap_sync_channel_write_layer4_out_11_V & ap_sync_channel_write_layer4_out_10_V & ap_sync_channel_write_layer4_out_0_V);

assign normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_ap_start = (layer2_out_9_V_empty_n & layer2_out_8_V_empty_n & layer2_out_7_V_empty_n & layer2_out_6_V_empty_n & layer2_out_5_V_empty_n & layer2_out_4_V_empty_n & layer2_out_3_V_empty_n & layer2_out_2_V_empty_n & layer2_out_1_V_empty_n & layer2_out_14_V_empty_n & layer2_out_13_V_empty_n & layer2_out_12_V_empty_n & layer2_out_11_V_empty_n & layer2_out_10_V_empty_n & layer2_out_0_V_empty_n);

assign normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_start_full_n = 1'b1;

assign normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_U0_start_write = 1'b0;

assign relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_continue = (ap_sync_channel_write_layer5_out_9_V & ap_sync_channel_write_layer5_out_8_V & ap_sync_channel_write_layer5_out_7_V & ap_sync_channel_write_layer5_out_6_V & ap_sync_channel_write_layer5_out_5_V & ap_sync_channel_write_layer5_out_4_V & ap_sync_channel_write_layer5_out_3_V & ap_sync_channel_write_layer5_out_2_V & ap_sync_channel_write_layer5_out_1_V & ap_sync_channel_write_layer5_out_14_V & ap_sync_channel_write_layer5_out_13_V & ap_sync_channel_write_layer5_out_12_V & ap_sync_channel_write_layer5_out_11_V & ap_sync_channel_write_layer5_out_10_V & ap_sync_channel_write_layer5_out_0_V);

assign relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_ap_start = (layer4_out_9_V_empty_n & layer4_out_8_V_empty_n & layer4_out_7_V_empty_n & layer4_out_6_V_empty_n & layer4_out_5_V_empty_n & layer4_out_4_V_empty_n & layer4_out_3_V_empty_n & layer4_out_2_V_empty_n & layer4_out_1_V_empty_n & layer4_out_14_V_empty_n & layer4_out_13_V_empty_n & layer4_out_12_V_empty_n & layer4_out_11_V_empty_n & layer4_out_10_V_empty_n & layer4_out_0_V_empty_n);

assign relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_start_full_n = 1'b1;

assign relu_ap_fixed_ap_ufixed_5_2_0_0_0_relu_config5_U0_start_write = 1'b0;

endmodule //myproject
