// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_14_V_read
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [4:0] data_0_V_read;
input  [4:0] data_1_V_read;
input  [4:0] data_2_V_read;
input  [4:0] data_3_V_read;
input  [4:0] data_4_V_read;
input  [4:0] data_5_V_read;
input  [4:0] data_6_V_read;
input  [4:0] data_7_V_read;
input  [4:0] data_8_V_read;
input  [4:0] data_9_V_read;
input  [4:0] data_10_V_read;
input  [4:0] data_11_V_read;
input  [4:0] data_12_V_read;
input  [4:0] data_13_V_read;
input  [4:0] data_14_V_read;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [1:0] w_index_fu_666_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] ap_phi_mux_do_init_phi_fu_166_p6;
reg   [0:0] do_init_reg_162;
wire   [0:0] icmp_ln64_fu_672_p2;
reg   [4:0] ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4;
reg   [4:0] data_0_V_read2_rewind_reg_177;
reg   [4:0] ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4;
reg   [4:0] data_1_V_read3_rewind_reg_191;
reg   [4:0] ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4;
reg   [4:0] data_2_V_read4_rewind_reg_205;
reg   [4:0] ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4;
reg   [4:0] data_3_V_read5_rewind_reg_219;
reg   [4:0] ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4;
reg   [4:0] data_4_V_read6_rewind_reg_233;
reg   [4:0] ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4;
reg   [4:0] data_5_V_read7_rewind_reg_247;
reg   [4:0] ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4;
reg   [4:0] data_6_V_read8_rewind_reg_261;
reg   [4:0] ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4;
reg   [4:0] data_7_V_read9_rewind_reg_275;
reg   [4:0] ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4;
reg   [4:0] data_8_V_read10_rewind_reg_289;
reg   [4:0] ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4;
reg   [4:0] data_9_V_read11_rewind_reg_303;
reg   [4:0] ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4;
reg   [4:0] data_10_V_read12_rewind_reg_317;
reg   [4:0] ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4;
reg   [4:0] data_11_V_read13_rewind_reg_331;
reg   [4:0] ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4;
reg   [4:0] data_12_V_read14_rewind_reg_345;
reg   [4:0] ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4;
reg   [4:0] data_13_V_read15_rewind_reg_359;
reg   [4:0] ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4;
reg   [4:0] data_14_V_read16_rewind_reg_373;
reg   [1:0] w_index1_reg_387;
wire   [4:0] phi_ln_fu_596_p6;
wire   [4:0] phi_ln77_1_fu_610_p6;
wire   [4:0] phi_ln77_2_fu_624_p6;
wire   [4:0] phi_ln77_3_fu_638_p6;
wire   [4:0] phi_ln77_4_fu_652_p6;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

myproject_mux_42_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 5 ),
    .din3_WIDTH( 5 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
myproject_mux_42_5_1_1_U69(
    .din0(ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4),
    .din1(ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4),
    .din2(ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4),
    .din3(ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4),
    .din4(w_index1_reg_387),
    .dout(phi_ln_fu_596_p6)
);

myproject_mux_42_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 5 ),
    .din3_WIDTH( 5 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
myproject_mux_42_5_1_1_U70(
    .din0(ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4),
    .din1(ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4),
    .din2(ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4),
    .din3(ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4),
    .din4(w_index1_reg_387),
    .dout(phi_ln77_1_fu_610_p6)
);

myproject_mux_42_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 5 ),
    .din3_WIDTH( 5 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
myproject_mux_42_5_1_1_U71(
    .din0(ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4),
    .din1(ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4),
    .din2(ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4),
    .din3(ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4),
    .din4(w_index1_reg_387),
    .dout(phi_ln77_2_fu_624_p6)
);

myproject_mux_42_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 5 ),
    .din3_WIDTH( 5 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
myproject_mux_42_5_1_1_U72(
    .din0(ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4),
    .din1(ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4),
    .din2(ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4),
    .din3(ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4),
    .din4(w_index1_reg_387),
    .dout(phi_ln77_3_fu_638_p6)
);

myproject_mux_42_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 5 ),
    .din3_WIDTH( 5 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
myproject_mux_42_5_1_1_U73(
    .din0(ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4),
    .din1(ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4),
    .din2(ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4),
    .din3(ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4),
    .din4(w_index1_reg_387),
    .dout(phi_ln77_4_fu_652_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (icmp_ln64_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        do_init_reg_162 <= 1'd0;
    end else if ((((ap_start == 1'b1) & (icmp_ln64_fu_672_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        do_init_reg_162 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (icmp_ln64_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        w_index1_reg_387 <= w_index_fu_666_p2;
    end else if ((((ap_start == 1'b1) & (icmp_ln64_fu_672_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        w_index1_reg_387 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (icmp_ln64_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        data_0_V_read2_rewind_reg_177 <= ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4;
        data_10_V_read12_rewind_reg_317 <= ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4;
        data_11_V_read13_rewind_reg_331 <= ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4;
        data_12_V_read14_rewind_reg_345 <= ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4;
        data_13_V_read15_rewind_reg_359 <= ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4;
        data_14_V_read16_rewind_reg_373 <= ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4;
        data_1_V_read3_rewind_reg_191 <= ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4;
        data_2_V_read4_rewind_reg_205 <= ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4;
        data_3_V_read5_rewind_reg_219 <= ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4;
        data_4_V_read6_rewind_reg_233 <= ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4;
        data_5_V_read7_rewind_reg_247 <= ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4;
        data_6_V_read8_rewind_reg_261 <= ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4;
        data_7_V_read9_rewind_reg_275 <= ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4;
        data_8_V_read10_rewind_reg_289 <= ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4;
        data_9_V_read11_rewind_reg_303 <= ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (icmp_ln64_fu_672_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd0)) begin
            ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4 = data_0_V_read2_rewind_reg_177;
        end else if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd1)) begin
            ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4 = data_0_V_read;
        end else begin
            ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd0)) begin
            ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4 = data_10_V_read12_rewind_reg_317;
        end else if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd1)) begin
            ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4 = data_10_V_read;
        end else begin
            ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd0)) begin
            ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4 = data_11_V_read13_rewind_reg_331;
        end else if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd1)) begin
            ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4 = data_11_V_read;
        end else begin
            ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd0)) begin
            ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4 = data_12_V_read14_rewind_reg_345;
        end else if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd1)) begin
            ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4 = data_12_V_read;
        end else begin
            ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd0)) begin
            ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4 = data_13_V_read15_rewind_reg_359;
        end else if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd1)) begin
            ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4 = data_13_V_read;
        end else begin
            ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd0)) begin
            ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4 = data_14_V_read16_rewind_reg_373;
        end else if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd1)) begin
            ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4 = data_14_V_read;
        end else begin
            ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd0)) begin
            ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4 = data_1_V_read3_rewind_reg_191;
        end else if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd1)) begin
            ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4 = data_1_V_read;
        end else begin
            ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd0)) begin
            ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4 = data_2_V_read4_rewind_reg_205;
        end else if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd1)) begin
            ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4 = data_2_V_read;
        end else begin
            ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd0)) begin
            ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4 = data_3_V_read5_rewind_reg_219;
        end else if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd1)) begin
            ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4 = data_3_V_read;
        end else begin
            ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd0)) begin
            ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4 = data_4_V_read6_rewind_reg_233;
        end else if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd1)) begin
            ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4 = data_4_V_read;
        end else begin
            ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd0)) begin
            ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4 = data_5_V_read7_rewind_reg_247;
        end else if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd1)) begin
            ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4 = data_5_V_read;
        end else begin
            ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd0)) begin
            ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4 = data_6_V_read8_rewind_reg_261;
        end else if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd1)) begin
            ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4 = data_6_V_read;
        end else begin
            ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd0)) begin
            ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4 = data_7_V_read9_rewind_reg_275;
        end else if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd1)) begin
            ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4 = data_7_V_read;
        end else begin
            ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd0)) begin
            ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4 = data_8_V_read10_rewind_reg_289;
        end else if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd1)) begin
            ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4 = data_8_V_read;
        end else begin
            ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd0)) begin
            ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4 = data_9_V_read11_rewind_reg_303;
        end else if ((ap_phi_mux_do_init_phi_fu_166_p6 == 1'd1)) begin
            ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4 = data_9_V_read;
        end else begin
            ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4 = 'bx;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (icmp_ln64_fu_672_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((ap_start == 1'b1) & (icmp_ln64_fu_672_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_phi_mux_do_init_phi_fu_166_p6 = do_init_reg_162;

assign icmp_ln64_fu_672_p2 = ((w_index1_reg_387 == 2'd2) ? 1'b1 : 1'b0);

assign w_index_fu_666_p2 = (w_index1_reg_387 + 2'd1);

endmodule //dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s
