// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Block_codeRepl320123320129_proc72.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Block_codeRepl320123320129_proc72::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Block_codeRepl320123320129_proc72::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> Block_codeRepl320123320129_proc72::ap_ST_fsm_state1 = "1";
const sc_lv<2> Block_codeRepl320123320129_proc72::ap_ST_fsm_state2 = "10";
const sc_lv<32> Block_codeRepl320123320129_proc72::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> Block_codeRepl320123320129_proc72::ap_const_lv32_1 = "1";
const sc_lv<128> Block_codeRepl320123320129_proc72::ap_const_lv128_lc_1 = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> Block_codeRepl320123320129_proc72::ap_const_lv112_1 = "1";
const sc_lv<32> Block_codeRepl320123320129_proc72::ap_const_lv32_8 = "1000";
const sc_lv<32> Block_codeRepl320123320129_proc72::ap_const_lv32_77 = "1110111";
const bool Block_codeRepl320123320129_proc72::ap_const_boolean_1 = true;

Block_codeRepl320123320129_proc72::Block_codeRepl320123320129_proc72(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157 = new dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s("grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157");
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->ap_clk(ap_clk);
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->ap_rst(ap_rst);
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->ap_start(grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_start);
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->ap_done(grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_done);
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->ap_idle(grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_idle);
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->ap_ready(grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_ready);
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->data_0_V_read(p_read);
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->data_1_V_read(p_read1);
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->data_2_V_read(p_read2);
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->data_3_V_read(p_read3);
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->data_4_V_read(p_read4);
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->data_5_V_read(p_read5);
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->data_6_V_read(p_read6);
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->data_7_V_read(p_read7);
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->data_8_V_read(p_read8);
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->data_9_V_read(p_read9);
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->data_10_V_read(p_read10);
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->data_11_V_read(p_read11);
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->data_12_V_read(p_read12);
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->data_13_V_read(p_read13);
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157->data_14_V_read(p_read14);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state1_ignore_call16);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_done );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_done );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_start);
    sensitive << ( grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_start_reg );

    SC_METHOD(thread_link_out_0_V_o);
    sensitive << ( grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_done );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( p_Result_s_fu_191_p5 );
    sensitive << ( link_out_0_V_o_preg );

    SC_METHOD(thread_link_out_0_V_o_ap_vld);
    sensitive << ( grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_done );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_p_Result_s_fu_191_p5);
    sensitive << ( link_out_0_V_i );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_done );
    sensitive << ( ap_CS_fsm_state2 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "01";
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_start_reg = SC_LOGIC_0;
    link_out_0_V_o_preg = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Block_codeRepl320123320129_proc72_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_read, "(port)p_read");
    sc_trace(mVcdFile, p_read1, "(port)p_read1");
    sc_trace(mVcdFile, p_read2, "(port)p_read2");
    sc_trace(mVcdFile, p_read3, "(port)p_read3");
    sc_trace(mVcdFile, p_read4, "(port)p_read4");
    sc_trace(mVcdFile, p_read5, "(port)p_read5");
    sc_trace(mVcdFile, p_read6, "(port)p_read6");
    sc_trace(mVcdFile, p_read7, "(port)p_read7");
    sc_trace(mVcdFile, p_read8, "(port)p_read8");
    sc_trace(mVcdFile, p_read9, "(port)p_read9");
    sc_trace(mVcdFile, p_read10, "(port)p_read10");
    sc_trace(mVcdFile, p_read11, "(port)p_read11");
    sc_trace(mVcdFile, p_read12, "(port)p_read12");
    sc_trace(mVcdFile, p_read13, "(port)p_read13");
    sc_trace(mVcdFile, p_read14, "(port)p_read14");
    sc_trace(mVcdFile, link_out_0_V_i, "(port)link_out_0_V_i");
    sc_trace(mVcdFile, link_out_0_V_o, "(port)link_out_0_V_o");
    sc_trace(mVcdFile, link_out_0_V_o_ap_vld, "(port)link_out_0_V_o_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_start, "grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_start");
    sc_trace(mVcdFile, grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_done, "grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_done");
    sc_trace(mVcdFile, grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_idle, "grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_idle");
    sc_trace(mVcdFile, grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_ready, "grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_ready");
    sc_trace(mVcdFile, grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_start_reg, "grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_start_reg");
    sc_trace(mVcdFile, ap_block_state1_ignore_call16, "ap_block_state1_ignore_call16");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, p_Result_s_fu_191_p5, "p_Result_s_fu_191_p5");
    sc_trace(mVcdFile, link_out_0_V_o_preg, "link_out_0_V_o_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

Block_codeRepl320123320129_proc72::~Block_codeRepl320123320129_proc72() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157;
}

void Block_codeRepl320123320129_proc72::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_done.read(), ap_const_logic_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_ready.read())) {
            grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        link_out_0_V_o_preg = ap_const_lv128_lc_1;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
             esl_seteq<1,1,1>(grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_done.read(), ap_const_logic_1))) {
            link_out_0_V_o_preg = p_Result_s_fu_191_p5.read();
        }
    }
}

void Block_codeRepl320123320129_proc72::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Block_codeRepl320123320129_proc72::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void Block_codeRepl320123320129_proc72::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void Block_codeRepl320123320129_proc72::thread_ap_block_state1_ignore_call16() {
    ap_block_state1_ignore_call16 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void Block_codeRepl320123320129_proc72::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_done.read(), ap_const_logic_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Block_codeRepl320123320129_proc72::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Block_codeRepl320123320129_proc72::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_done.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Block_codeRepl320123320129_proc72::thread_grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_start() {
    grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_start = grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_start_reg.read();
}

void Block_codeRepl320123320129_proc72::thread_link_out_0_V_o() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_done.read(), ap_const_logic_1))) {
        link_out_0_V_o = p_Result_s_fu_191_p5.read();
    } else {
        link_out_0_V_o = link_out_0_V_o_preg.read();
    }
}

void Block_codeRepl320123320129_proc72::thread_link_out_0_V_o_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_done.read(), ap_const_logic_1))) {
        link_out_0_V_o_ap_vld = ap_const_logic_1;
    } else {
        link_out_0_V_o_ap_vld = ap_const_logic_0;
    }
}

void Block_codeRepl320123320129_proc72::thread_p_Result_s_fu_191_p5() {
    p_Result_s_fu_191_p5 = esl_partset<128,128,112,32,32>(link_out_0_V_i.read(), ap_const_lv112_1, ap_const_lv32_8, ap_const_lv32_77);
}

void Block_codeRepl320123320129_proc72::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(grp_dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_fu_157_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

