// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_HH_
#define _dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "myproject_mux_42_5_1_1.h"

namespace ap_rtl {

struct dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s : public sc_module {
    // Port declarations 21
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<5> > data_0_V_read;
    sc_in< sc_lv<5> > data_1_V_read;
    sc_in< sc_lv<5> > data_2_V_read;
    sc_in< sc_lv<5> > data_3_V_read;
    sc_in< sc_lv<5> > data_4_V_read;
    sc_in< sc_lv<5> > data_5_V_read;
    sc_in< sc_lv<5> > data_6_V_read;
    sc_in< sc_lv<5> > data_7_V_read;
    sc_in< sc_lv<5> > data_8_V_read;
    sc_in< sc_lv<5> > data_9_V_read;
    sc_in< sc_lv<5> > data_10_V_read;
    sc_in< sc_lv<5> > data_11_V_read;
    sc_in< sc_lv<5> > data_12_V_read;
    sc_in< sc_lv<5> > data_13_V_read;
    sc_in< sc_lv<5> > data_14_V_read;


    // Module declarations
    dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s(sc_module_name name);
    SC_HAS_PROCESS(dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s);

    ~dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s();

    sc_trace_file* mVcdFile;

    myproject_mux_42_5_1_1<1,1,5,5,5,5,2,5>* myproject_mux_42_5_1_1_U69;
    myproject_mux_42_5_1_1<1,1,5,5,5,5,2,5>* myproject_mux_42_5_1_1_U70;
    myproject_mux_42_5_1_1<1,1,5,5,5,5,2,5>* myproject_mux_42_5_1_1_U71;
    myproject_mux_42_5_1_1<1,1,5,5,5,5,2,5>* myproject_mux_42_5_1_1_U72;
    myproject_mux_42_5_1_1<1,1,5,5,5,5,2,5>* myproject_mux_42_5_1_1_U73;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<2> > w_index_fu_666_p2;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > ap_phi_mux_do_init_phi_fu_166_p6;
    sc_signal< sc_lv<1> > do_init_reg_162;
    sc_signal< sc_lv<1> > icmp_ln64_fu_672_p2;
    sc_signal< sc_lv<5> > ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4;
    sc_signal< sc_lv<5> > data_0_V_read2_rewind_reg_177;
    sc_signal< sc_lv<5> > ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4;
    sc_signal< sc_lv<5> > data_1_V_read3_rewind_reg_191;
    sc_signal< sc_lv<5> > ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4;
    sc_signal< sc_lv<5> > data_2_V_read4_rewind_reg_205;
    sc_signal< sc_lv<5> > ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4;
    sc_signal< sc_lv<5> > data_3_V_read5_rewind_reg_219;
    sc_signal< sc_lv<5> > ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4;
    sc_signal< sc_lv<5> > data_4_V_read6_rewind_reg_233;
    sc_signal< sc_lv<5> > ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4;
    sc_signal< sc_lv<5> > data_5_V_read7_rewind_reg_247;
    sc_signal< sc_lv<5> > ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4;
    sc_signal< sc_lv<5> > data_6_V_read8_rewind_reg_261;
    sc_signal< sc_lv<5> > ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4;
    sc_signal< sc_lv<5> > data_7_V_read9_rewind_reg_275;
    sc_signal< sc_lv<5> > ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4;
    sc_signal< sc_lv<5> > data_8_V_read10_rewind_reg_289;
    sc_signal< sc_lv<5> > ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4;
    sc_signal< sc_lv<5> > data_9_V_read11_rewind_reg_303;
    sc_signal< sc_lv<5> > ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4;
    sc_signal< sc_lv<5> > data_10_V_read12_rewind_reg_317;
    sc_signal< sc_lv<5> > ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4;
    sc_signal< sc_lv<5> > data_11_V_read13_rewind_reg_331;
    sc_signal< sc_lv<5> > ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4;
    sc_signal< sc_lv<5> > data_12_V_read14_rewind_reg_345;
    sc_signal< sc_lv<5> > ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4;
    sc_signal< sc_lv<5> > data_13_V_read15_rewind_reg_359;
    sc_signal< sc_lv<5> > ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4;
    sc_signal< sc_lv<5> > data_14_V_read16_rewind_reg_373;
    sc_signal< sc_lv<2> > w_index1_reg_387;
    sc_signal< sc_lv<5> > phi_ln_fu_596_p6;
    sc_signal< sc_lv<5> > phi_ln77_1_fu_610_p6;
    sc_signal< sc_lv<5> > phi_ln77_2_fu_624_p6;
    sc_signal< sc_lv<5> > phi_ln77_3_fu_638_p6;
    sc_signal< sc_lv<5> > phi_ln77_4_fu_652_p6;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<2> ap_const_lv2_2;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4();
    void thread_ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4();
    void thread_ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4();
    void thread_ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4();
    void thread_ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4();
    void thread_ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4();
    void thread_ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4();
    void thread_ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4();
    void thread_ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4();
    void thread_ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4();
    void thread_ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4();
    void thread_ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4();
    void thread_ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4();
    void thread_ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4();
    void thread_ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4();
    void thread_ap_phi_mux_do_init_phi_fu_166_p6();
    void thread_ap_ready();
    void thread_icmp_ln64_fu_672_p2();
    void thread_w_index_fu_666_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
