// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::ap_ST_fsm_state1 = "1";
const sc_lv<32> normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<10> normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::ap_const_lv10_0 = "0000000000";
const sc_lv<32> normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::ap_const_lv32_2 = "10";
const sc_lv<32> normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::ap_const_lv32_15 = "10101";
const sc_lv<20> normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::ap_const_lv20_0 = "00000000000000000000";
const bool normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::ap_const_boolean_1 = true;

normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( sub_ln1118_fu_172_p2 );
    sensitive << ( ap_return_0_preg );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( sub_ln1118_1_fu_204_p2 );
    sensitive << ( ap_return_1_preg );

    SC_METHOD(thread_ap_return_10);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( sub_ln1118_10_fu_492_p2 );
    sensitive << ( ap_return_10_preg );

    SC_METHOD(thread_ap_return_11);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( sub_ln1118_11_fu_524_p2 );
    sensitive << ( ap_return_11_preg );

    SC_METHOD(thread_ap_return_12);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( sub_ln1118_12_fu_556_p2 );
    sensitive << ( ap_return_12_preg );

    SC_METHOD(thread_ap_return_13);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( sub_ln1118_13_fu_588_p2 );
    sensitive << ( ap_return_13_preg );

    SC_METHOD(thread_ap_return_14);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( sub_ln1118_14_fu_620_p2 );
    sensitive << ( ap_return_14_preg );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( sub_ln1118_2_fu_236_p2 );
    sensitive << ( ap_return_2_preg );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( sub_ln1118_3_fu_268_p2 );
    sensitive << ( ap_return_3_preg );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( sub_ln1118_4_fu_300_p2 );
    sensitive << ( ap_return_4_preg );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( sub_ln1118_5_fu_332_p2 );
    sensitive << ( ap_return_5_preg );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( sub_ln1118_6_fu_364_p2 );
    sensitive << ( ap_return_6_preg );

    SC_METHOD(thread_ap_return_7);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( sub_ln1118_7_fu_396_p2 );
    sensitive << ( ap_return_7_preg );

    SC_METHOD(thread_ap_return_8);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( sub_ln1118_8_fu_428_p2 );
    sensitive << ( ap_return_8_preg );

    SC_METHOD(thread_ap_return_9);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( sub_ln1118_9_fu_460_p2 );
    sensitive << ( ap_return_9_preg );

    SC_METHOD(thread_sext_ln1118_10_fu_476_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read10 );

    SC_METHOD(thread_sext_ln1118_10_fu_476_p1);
    sensitive << ( sext_ln1118_10_fu_476_p0 );

    SC_METHOD(thread_sext_ln1118_11_fu_508_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read11 );

    SC_METHOD(thread_sext_ln1118_11_fu_508_p1);
    sensitive << ( sext_ln1118_11_fu_508_p0 );

    SC_METHOD(thread_sext_ln1118_12_fu_540_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read12 );

    SC_METHOD(thread_sext_ln1118_12_fu_540_p1);
    sensitive << ( sext_ln1118_12_fu_540_p0 );

    SC_METHOD(thread_sext_ln1118_13_fu_572_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read13 );

    SC_METHOD(thread_sext_ln1118_13_fu_572_p1);
    sensitive << ( sext_ln1118_13_fu_572_p0 );

    SC_METHOD(thread_sext_ln1118_14_fu_604_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read14 );

    SC_METHOD(thread_sext_ln1118_14_fu_604_p1);
    sensitive << ( sext_ln1118_14_fu_604_p0 );

    SC_METHOD(thread_sext_ln1118_1_fu_188_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read1 );

    SC_METHOD(thread_sext_ln1118_1_fu_188_p1);
    sensitive << ( sext_ln1118_1_fu_188_p0 );

    SC_METHOD(thread_sext_ln1118_2_fu_220_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read2 );

    SC_METHOD(thread_sext_ln1118_2_fu_220_p1);
    sensitive << ( sext_ln1118_2_fu_220_p0 );

    SC_METHOD(thread_sext_ln1118_3_fu_252_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read3 );

    SC_METHOD(thread_sext_ln1118_3_fu_252_p1);
    sensitive << ( sext_ln1118_3_fu_252_p0 );

    SC_METHOD(thread_sext_ln1118_4_fu_284_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read4 );

    SC_METHOD(thread_sext_ln1118_4_fu_284_p1);
    sensitive << ( sext_ln1118_4_fu_284_p0 );

    SC_METHOD(thread_sext_ln1118_5_fu_316_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read5 );

    SC_METHOD(thread_sext_ln1118_5_fu_316_p1);
    sensitive << ( sext_ln1118_5_fu_316_p0 );

    SC_METHOD(thread_sext_ln1118_6_fu_348_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read6 );

    SC_METHOD(thread_sext_ln1118_6_fu_348_p1);
    sensitive << ( sext_ln1118_6_fu_348_p0 );

    SC_METHOD(thread_sext_ln1118_7_fu_380_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read7 );

    SC_METHOD(thread_sext_ln1118_7_fu_380_p1);
    sensitive << ( sext_ln1118_7_fu_380_p0 );

    SC_METHOD(thread_sext_ln1118_8_fu_412_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read8 );

    SC_METHOD(thread_sext_ln1118_8_fu_412_p1);
    sensitive << ( sext_ln1118_8_fu_412_p0 );

    SC_METHOD(thread_sext_ln1118_9_fu_444_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read9 );

    SC_METHOD(thread_sext_ln1118_9_fu_444_p1);
    sensitive << ( sext_ln1118_9_fu_444_p0 );

    SC_METHOD(thread_sext_ln1118_fu_156_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read );

    SC_METHOD(thread_sext_ln1118_fu_156_p1);
    sensitive << ( sext_ln1118_fu_156_p0 );

    SC_METHOD(thread_shl_ln1118_10_fu_516_p3);
    sensitive << ( trunc_ln1118_11_fu_512_p1 );

    SC_METHOD(thread_shl_ln1118_11_fu_548_p3);
    sensitive << ( trunc_ln1118_12_fu_544_p1 );

    SC_METHOD(thread_shl_ln1118_12_fu_580_p3);
    sensitive << ( trunc_ln1118_13_fu_576_p1 );

    SC_METHOD(thread_shl_ln1118_13_fu_612_p3);
    sensitive << ( trunc_ln1118_14_fu_608_p1 );

    SC_METHOD(thread_shl_ln1118_1_fu_196_p3);
    sensitive << ( trunc_ln1118_1_fu_192_p1 );

    SC_METHOD(thread_shl_ln1118_2_fu_228_p3);
    sensitive << ( trunc_ln1118_2_fu_224_p1 );

    SC_METHOD(thread_shl_ln1118_3_fu_260_p3);
    sensitive << ( trunc_ln1118_3_fu_256_p1 );

    SC_METHOD(thread_shl_ln1118_4_fu_292_p3);
    sensitive << ( trunc_ln1118_4_fu_288_p1 );

    SC_METHOD(thread_shl_ln1118_5_fu_324_p3);
    sensitive << ( trunc_ln1118_5_fu_320_p1 );

    SC_METHOD(thread_shl_ln1118_6_fu_356_p3);
    sensitive << ( trunc_ln1118_6_fu_352_p1 );

    SC_METHOD(thread_shl_ln1118_7_fu_388_p3);
    sensitive << ( trunc_ln1118_7_fu_384_p1 );

    SC_METHOD(thread_shl_ln1118_8_fu_420_p3);
    sensitive << ( trunc_ln1118_8_fu_416_p1 );

    SC_METHOD(thread_shl_ln1118_9_fu_452_p3);
    sensitive << ( trunc_ln1118_9_fu_448_p1 );

    SC_METHOD(thread_shl_ln1118_s_fu_484_p3);
    sensitive << ( trunc_ln1118_10_fu_480_p1 );

    SC_METHOD(thread_shl_ln_fu_164_p3);
    sensitive << ( trunc_ln1118_fu_160_p1 );

    SC_METHOD(thread_sub_ln1118_10_fu_492_p2);
    sensitive << ( shl_ln1118_s_fu_484_p3 );
    sensitive << ( sext_ln1118_10_fu_476_p1 );

    SC_METHOD(thread_sub_ln1118_11_fu_524_p2);
    sensitive << ( shl_ln1118_10_fu_516_p3 );
    sensitive << ( sext_ln1118_11_fu_508_p1 );

    SC_METHOD(thread_sub_ln1118_12_fu_556_p2);
    sensitive << ( shl_ln1118_11_fu_548_p3 );
    sensitive << ( sext_ln1118_12_fu_540_p1 );

    SC_METHOD(thread_sub_ln1118_13_fu_588_p2);
    sensitive << ( shl_ln1118_12_fu_580_p3 );
    sensitive << ( sext_ln1118_13_fu_572_p1 );

    SC_METHOD(thread_sub_ln1118_14_fu_620_p2);
    sensitive << ( shl_ln1118_13_fu_612_p3 );
    sensitive << ( sext_ln1118_14_fu_604_p1 );

    SC_METHOD(thread_sub_ln1118_1_fu_204_p2);
    sensitive << ( shl_ln1118_1_fu_196_p3 );
    sensitive << ( sext_ln1118_1_fu_188_p1 );

    SC_METHOD(thread_sub_ln1118_2_fu_236_p2);
    sensitive << ( shl_ln1118_2_fu_228_p3 );
    sensitive << ( sext_ln1118_2_fu_220_p1 );

    SC_METHOD(thread_sub_ln1118_3_fu_268_p2);
    sensitive << ( shl_ln1118_3_fu_260_p3 );
    sensitive << ( sext_ln1118_3_fu_252_p1 );

    SC_METHOD(thread_sub_ln1118_4_fu_300_p2);
    sensitive << ( shl_ln1118_4_fu_292_p3 );
    sensitive << ( sext_ln1118_4_fu_284_p1 );

    SC_METHOD(thread_sub_ln1118_5_fu_332_p2);
    sensitive << ( shl_ln1118_5_fu_324_p3 );
    sensitive << ( sext_ln1118_5_fu_316_p1 );

    SC_METHOD(thread_sub_ln1118_6_fu_364_p2);
    sensitive << ( shl_ln1118_6_fu_356_p3 );
    sensitive << ( sext_ln1118_6_fu_348_p1 );

    SC_METHOD(thread_sub_ln1118_7_fu_396_p2);
    sensitive << ( shl_ln1118_7_fu_388_p3 );
    sensitive << ( sext_ln1118_7_fu_380_p1 );

    SC_METHOD(thread_sub_ln1118_8_fu_428_p2);
    sensitive << ( shl_ln1118_8_fu_420_p3 );
    sensitive << ( sext_ln1118_8_fu_412_p1 );

    SC_METHOD(thread_sub_ln1118_9_fu_460_p2);
    sensitive << ( shl_ln1118_9_fu_452_p3 );
    sensitive << ( sext_ln1118_9_fu_444_p1 );

    SC_METHOD(thread_sub_ln1118_fu_172_p2);
    sensitive << ( shl_ln_fu_164_p3 );
    sensitive << ( sext_ln1118_fu_156_p1 );

    SC_METHOD(thread_trunc_ln1118_10_fu_480_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read10 );

    SC_METHOD(thread_trunc_ln1118_10_fu_480_p1);
    sensitive << ( trunc_ln1118_10_fu_480_p0 );

    SC_METHOD(thread_trunc_ln1118_11_fu_512_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read11 );

    SC_METHOD(thread_trunc_ln1118_11_fu_512_p1);
    sensitive << ( trunc_ln1118_11_fu_512_p0 );

    SC_METHOD(thread_trunc_ln1118_12_fu_544_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read12 );

    SC_METHOD(thread_trunc_ln1118_12_fu_544_p1);
    sensitive << ( trunc_ln1118_12_fu_544_p0 );

    SC_METHOD(thread_trunc_ln1118_13_fu_576_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read13 );

    SC_METHOD(thread_trunc_ln1118_13_fu_576_p1);
    sensitive << ( trunc_ln1118_13_fu_576_p0 );

    SC_METHOD(thread_trunc_ln1118_14_fu_608_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read14 );

    SC_METHOD(thread_trunc_ln1118_14_fu_608_p1);
    sensitive << ( trunc_ln1118_14_fu_608_p0 );

    SC_METHOD(thread_trunc_ln1118_1_fu_192_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read1 );

    SC_METHOD(thread_trunc_ln1118_1_fu_192_p1);
    sensitive << ( trunc_ln1118_1_fu_192_p0 );

    SC_METHOD(thread_trunc_ln1118_2_fu_224_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read2 );

    SC_METHOD(thread_trunc_ln1118_2_fu_224_p1);
    sensitive << ( trunc_ln1118_2_fu_224_p0 );

    SC_METHOD(thread_trunc_ln1118_3_fu_256_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read3 );

    SC_METHOD(thread_trunc_ln1118_3_fu_256_p1);
    sensitive << ( trunc_ln1118_3_fu_256_p0 );

    SC_METHOD(thread_trunc_ln1118_4_fu_288_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read4 );

    SC_METHOD(thread_trunc_ln1118_4_fu_288_p1);
    sensitive << ( trunc_ln1118_4_fu_288_p0 );

    SC_METHOD(thread_trunc_ln1118_5_fu_320_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read5 );

    SC_METHOD(thread_trunc_ln1118_5_fu_320_p1);
    sensitive << ( trunc_ln1118_5_fu_320_p0 );

    SC_METHOD(thread_trunc_ln1118_6_fu_352_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read6 );

    SC_METHOD(thread_trunc_ln1118_6_fu_352_p1);
    sensitive << ( trunc_ln1118_6_fu_352_p0 );

    SC_METHOD(thread_trunc_ln1118_7_fu_384_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read7 );

    SC_METHOD(thread_trunc_ln1118_7_fu_384_p1);
    sensitive << ( trunc_ln1118_7_fu_384_p0 );

    SC_METHOD(thread_trunc_ln1118_8_fu_416_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read8 );

    SC_METHOD(thread_trunc_ln1118_8_fu_416_p1);
    sensitive << ( trunc_ln1118_8_fu_416_p0 );

    SC_METHOD(thread_trunc_ln1118_9_fu_448_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read9 );

    SC_METHOD(thread_trunc_ln1118_9_fu_448_p1);
    sensitive << ( trunc_ln1118_9_fu_448_p0 );

    SC_METHOD(thread_trunc_ln1118_fu_160_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read );

    SC_METHOD(thread_trunc_ln1118_fu_160_p1);
    sensitive << ( trunc_ln1118_fu_160_p0 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "1";
    ap_return_0_preg = "00000000000000000000";
    ap_return_1_preg = "00000000000000000000";
    ap_return_2_preg = "00000000000000000000";
    ap_return_3_preg = "00000000000000000000";
    ap_return_4_preg = "00000000000000000000";
    ap_return_5_preg = "00000000000000000000";
    ap_return_6_preg = "00000000000000000000";
    ap_return_7_preg = "00000000000000000000";
    ap_return_8_preg = "00000000000000000000";
    ap_return_9_preg = "00000000000000000000";
    ap_return_10_preg = "00000000000000000000";
    ap_return_11_preg = "00000000000000000000";
    ap_return_12_preg = "00000000000000000000";
    ap_return_13_preg = "00000000000000000000";
    ap_return_14_preg = "00000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_read, "(port)p_read");
    sc_trace(mVcdFile, p_read1, "(port)p_read1");
    sc_trace(mVcdFile, p_read2, "(port)p_read2");
    sc_trace(mVcdFile, p_read3, "(port)p_read3");
    sc_trace(mVcdFile, p_read4, "(port)p_read4");
    sc_trace(mVcdFile, p_read5, "(port)p_read5");
    sc_trace(mVcdFile, p_read6, "(port)p_read6");
    sc_trace(mVcdFile, p_read7, "(port)p_read7");
    sc_trace(mVcdFile, p_read8, "(port)p_read8");
    sc_trace(mVcdFile, p_read9, "(port)p_read9");
    sc_trace(mVcdFile, p_read10, "(port)p_read10");
    sc_trace(mVcdFile, p_read11, "(port)p_read11");
    sc_trace(mVcdFile, p_read12, "(port)p_read12");
    sc_trace(mVcdFile, p_read13, "(port)p_read13");
    sc_trace(mVcdFile, p_read14, "(port)p_read14");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
    sc_trace(mVcdFile, ap_return_7, "(port)ap_return_7");
    sc_trace(mVcdFile, ap_return_8, "(port)ap_return_8");
    sc_trace(mVcdFile, ap_return_9, "(port)ap_return_9");
    sc_trace(mVcdFile, ap_return_10, "(port)ap_return_10");
    sc_trace(mVcdFile, ap_return_11, "(port)ap_return_11");
    sc_trace(mVcdFile, ap_return_12, "(port)ap_return_12");
    sc_trace(mVcdFile, ap_return_13, "(port)ap_return_13");
    sc_trace(mVcdFile, ap_return_14, "(port)ap_return_14");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, sext_ln1118_fu_156_p0, "sext_ln1118_fu_156_p0");
    sc_trace(mVcdFile, trunc_ln1118_fu_160_p0, "trunc_ln1118_fu_160_p0");
    sc_trace(mVcdFile, trunc_ln1118_fu_160_p1, "trunc_ln1118_fu_160_p1");
    sc_trace(mVcdFile, shl_ln_fu_164_p3, "shl_ln_fu_164_p3");
    sc_trace(mVcdFile, sext_ln1118_fu_156_p1, "sext_ln1118_fu_156_p1");
    sc_trace(mVcdFile, sub_ln1118_fu_172_p2, "sub_ln1118_fu_172_p2");
    sc_trace(mVcdFile, sext_ln1118_1_fu_188_p0, "sext_ln1118_1_fu_188_p0");
    sc_trace(mVcdFile, trunc_ln1118_1_fu_192_p0, "trunc_ln1118_1_fu_192_p0");
    sc_trace(mVcdFile, trunc_ln1118_1_fu_192_p1, "trunc_ln1118_1_fu_192_p1");
    sc_trace(mVcdFile, shl_ln1118_1_fu_196_p3, "shl_ln1118_1_fu_196_p3");
    sc_trace(mVcdFile, sext_ln1118_1_fu_188_p1, "sext_ln1118_1_fu_188_p1");
    sc_trace(mVcdFile, sub_ln1118_1_fu_204_p2, "sub_ln1118_1_fu_204_p2");
    sc_trace(mVcdFile, sext_ln1118_2_fu_220_p0, "sext_ln1118_2_fu_220_p0");
    sc_trace(mVcdFile, trunc_ln1118_2_fu_224_p0, "trunc_ln1118_2_fu_224_p0");
    sc_trace(mVcdFile, trunc_ln1118_2_fu_224_p1, "trunc_ln1118_2_fu_224_p1");
    sc_trace(mVcdFile, shl_ln1118_2_fu_228_p3, "shl_ln1118_2_fu_228_p3");
    sc_trace(mVcdFile, sext_ln1118_2_fu_220_p1, "sext_ln1118_2_fu_220_p1");
    sc_trace(mVcdFile, sub_ln1118_2_fu_236_p2, "sub_ln1118_2_fu_236_p2");
    sc_trace(mVcdFile, sext_ln1118_3_fu_252_p0, "sext_ln1118_3_fu_252_p0");
    sc_trace(mVcdFile, trunc_ln1118_3_fu_256_p0, "trunc_ln1118_3_fu_256_p0");
    sc_trace(mVcdFile, trunc_ln1118_3_fu_256_p1, "trunc_ln1118_3_fu_256_p1");
    sc_trace(mVcdFile, shl_ln1118_3_fu_260_p3, "shl_ln1118_3_fu_260_p3");
    sc_trace(mVcdFile, sext_ln1118_3_fu_252_p1, "sext_ln1118_3_fu_252_p1");
    sc_trace(mVcdFile, sub_ln1118_3_fu_268_p2, "sub_ln1118_3_fu_268_p2");
    sc_trace(mVcdFile, sext_ln1118_4_fu_284_p0, "sext_ln1118_4_fu_284_p0");
    sc_trace(mVcdFile, trunc_ln1118_4_fu_288_p0, "trunc_ln1118_4_fu_288_p0");
    sc_trace(mVcdFile, trunc_ln1118_4_fu_288_p1, "trunc_ln1118_4_fu_288_p1");
    sc_trace(mVcdFile, shl_ln1118_4_fu_292_p3, "shl_ln1118_4_fu_292_p3");
    sc_trace(mVcdFile, sext_ln1118_4_fu_284_p1, "sext_ln1118_4_fu_284_p1");
    sc_trace(mVcdFile, sub_ln1118_4_fu_300_p2, "sub_ln1118_4_fu_300_p2");
    sc_trace(mVcdFile, sext_ln1118_5_fu_316_p0, "sext_ln1118_5_fu_316_p0");
    sc_trace(mVcdFile, trunc_ln1118_5_fu_320_p0, "trunc_ln1118_5_fu_320_p0");
    sc_trace(mVcdFile, trunc_ln1118_5_fu_320_p1, "trunc_ln1118_5_fu_320_p1");
    sc_trace(mVcdFile, shl_ln1118_5_fu_324_p3, "shl_ln1118_5_fu_324_p3");
    sc_trace(mVcdFile, sext_ln1118_5_fu_316_p1, "sext_ln1118_5_fu_316_p1");
    sc_trace(mVcdFile, sub_ln1118_5_fu_332_p2, "sub_ln1118_5_fu_332_p2");
    sc_trace(mVcdFile, sext_ln1118_6_fu_348_p0, "sext_ln1118_6_fu_348_p0");
    sc_trace(mVcdFile, trunc_ln1118_6_fu_352_p0, "trunc_ln1118_6_fu_352_p0");
    sc_trace(mVcdFile, trunc_ln1118_6_fu_352_p1, "trunc_ln1118_6_fu_352_p1");
    sc_trace(mVcdFile, shl_ln1118_6_fu_356_p3, "shl_ln1118_6_fu_356_p3");
    sc_trace(mVcdFile, sext_ln1118_6_fu_348_p1, "sext_ln1118_6_fu_348_p1");
    sc_trace(mVcdFile, sub_ln1118_6_fu_364_p2, "sub_ln1118_6_fu_364_p2");
    sc_trace(mVcdFile, sext_ln1118_7_fu_380_p0, "sext_ln1118_7_fu_380_p0");
    sc_trace(mVcdFile, trunc_ln1118_7_fu_384_p0, "trunc_ln1118_7_fu_384_p0");
    sc_trace(mVcdFile, trunc_ln1118_7_fu_384_p1, "trunc_ln1118_7_fu_384_p1");
    sc_trace(mVcdFile, shl_ln1118_7_fu_388_p3, "shl_ln1118_7_fu_388_p3");
    sc_trace(mVcdFile, sext_ln1118_7_fu_380_p1, "sext_ln1118_7_fu_380_p1");
    sc_trace(mVcdFile, sub_ln1118_7_fu_396_p2, "sub_ln1118_7_fu_396_p2");
    sc_trace(mVcdFile, sext_ln1118_8_fu_412_p0, "sext_ln1118_8_fu_412_p0");
    sc_trace(mVcdFile, trunc_ln1118_8_fu_416_p0, "trunc_ln1118_8_fu_416_p0");
    sc_trace(mVcdFile, trunc_ln1118_8_fu_416_p1, "trunc_ln1118_8_fu_416_p1");
    sc_trace(mVcdFile, shl_ln1118_8_fu_420_p3, "shl_ln1118_8_fu_420_p3");
    sc_trace(mVcdFile, sext_ln1118_8_fu_412_p1, "sext_ln1118_8_fu_412_p1");
    sc_trace(mVcdFile, sub_ln1118_8_fu_428_p2, "sub_ln1118_8_fu_428_p2");
    sc_trace(mVcdFile, sext_ln1118_9_fu_444_p0, "sext_ln1118_9_fu_444_p0");
    sc_trace(mVcdFile, trunc_ln1118_9_fu_448_p0, "trunc_ln1118_9_fu_448_p0");
    sc_trace(mVcdFile, trunc_ln1118_9_fu_448_p1, "trunc_ln1118_9_fu_448_p1");
    sc_trace(mVcdFile, shl_ln1118_9_fu_452_p3, "shl_ln1118_9_fu_452_p3");
    sc_trace(mVcdFile, sext_ln1118_9_fu_444_p1, "sext_ln1118_9_fu_444_p1");
    sc_trace(mVcdFile, sub_ln1118_9_fu_460_p2, "sub_ln1118_9_fu_460_p2");
    sc_trace(mVcdFile, sext_ln1118_10_fu_476_p0, "sext_ln1118_10_fu_476_p0");
    sc_trace(mVcdFile, trunc_ln1118_10_fu_480_p0, "trunc_ln1118_10_fu_480_p0");
    sc_trace(mVcdFile, trunc_ln1118_10_fu_480_p1, "trunc_ln1118_10_fu_480_p1");
    sc_trace(mVcdFile, shl_ln1118_s_fu_484_p3, "shl_ln1118_s_fu_484_p3");
    sc_trace(mVcdFile, sext_ln1118_10_fu_476_p1, "sext_ln1118_10_fu_476_p1");
    sc_trace(mVcdFile, sub_ln1118_10_fu_492_p2, "sub_ln1118_10_fu_492_p2");
    sc_trace(mVcdFile, sext_ln1118_11_fu_508_p0, "sext_ln1118_11_fu_508_p0");
    sc_trace(mVcdFile, trunc_ln1118_11_fu_512_p0, "trunc_ln1118_11_fu_512_p0");
    sc_trace(mVcdFile, trunc_ln1118_11_fu_512_p1, "trunc_ln1118_11_fu_512_p1");
    sc_trace(mVcdFile, shl_ln1118_10_fu_516_p3, "shl_ln1118_10_fu_516_p3");
    sc_trace(mVcdFile, sext_ln1118_11_fu_508_p1, "sext_ln1118_11_fu_508_p1");
    sc_trace(mVcdFile, sub_ln1118_11_fu_524_p2, "sub_ln1118_11_fu_524_p2");
    sc_trace(mVcdFile, sext_ln1118_12_fu_540_p0, "sext_ln1118_12_fu_540_p0");
    sc_trace(mVcdFile, trunc_ln1118_12_fu_544_p0, "trunc_ln1118_12_fu_544_p0");
    sc_trace(mVcdFile, trunc_ln1118_12_fu_544_p1, "trunc_ln1118_12_fu_544_p1");
    sc_trace(mVcdFile, shl_ln1118_11_fu_548_p3, "shl_ln1118_11_fu_548_p3");
    sc_trace(mVcdFile, sext_ln1118_12_fu_540_p1, "sext_ln1118_12_fu_540_p1");
    sc_trace(mVcdFile, sub_ln1118_12_fu_556_p2, "sub_ln1118_12_fu_556_p2");
    sc_trace(mVcdFile, sext_ln1118_13_fu_572_p0, "sext_ln1118_13_fu_572_p0");
    sc_trace(mVcdFile, trunc_ln1118_13_fu_576_p0, "trunc_ln1118_13_fu_576_p0");
    sc_trace(mVcdFile, trunc_ln1118_13_fu_576_p1, "trunc_ln1118_13_fu_576_p1");
    sc_trace(mVcdFile, shl_ln1118_12_fu_580_p3, "shl_ln1118_12_fu_580_p3");
    sc_trace(mVcdFile, sext_ln1118_13_fu_572_p1, "sext_ln1118_13_fu_572_p1");
    sc_trace(mVcdFile, sub_ln1118_13_fu_588_p2, "sub_ln1118_13_fu_588_p2");
    sc_trace(mVcdFile, sext_ln1118_14_fu_604_p0, "sext_ln1118_14_fu_604_p0");
    sc_trace(mVcdFile, trunc_ln1118_14_fu_608_p0, "trunc_ln1118_14_fu_608_p0");
    sc_trace(mVcdFile, trunc_ln1118_14_fu_608_p1, "trunc_ln1118_14_fu_608_p1");
    sc_trace(mVcdFile, shl_ln1118_13_fu_612_p3, "shl_ln1118_13_fu_612_p3");
    sc_trace(mVcdFile, sext_ln1118_14_fu_604_p1, "sext_ln1118_14_fu_604_p1");
    sc_trace(mVcdFile, sub_ln1118_14_fu_620_p2, "sub_ln1118_14_fu_620_p2");
    sc_trace(mVcdFile, ap_return_0_preg, "ap_return_0_preg");
    sc_trace(mVcdFile, ap_return_1_preg, "ap_return_1_preg");
    sc_trace(mVcdFile, ap_return_2_preg, "ap_return_2_preg");
    sc_trace(mVcdFile, ap_return_3_preg, "ap_return_3_preg");
    sc_trace(mVcdFile, ap_return_4_preg, "ap_return_4_preg");
    sc_trace(mVcdFile, ap_return_5_preg, "ap_return_5_preg");
    sc_trace(mVcdFile, ap_return_6_preg, "ap_return_6_preg");
    sc_trace(mVcdFile, ap_return_7_preg, "ap_return_7_preg");
    sc_trace(mVcdFile, ap_return_8_preg, "ap_return_8_preg");
    sc_trace(mVcdFile, ap_return_9_preg, "ap_return_9_preg");
    sc_trace(mVcdFile, ap_return_10_preg, "ap_return_10_preg");
    sc_trace(mVcdFile, ap_return_11_preg, "ap_return_11_preg");
    sc_trace(mVcdFile, ap_return_12_preg, "ap_return_12_preg");
    sc_trace(mVcdFile, ap_return_13_preg, "ap_return_13_preg");
    sc_trace(mVcdFile, ap_return_14_preg, "ap_return_14_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::~normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_0_preg = ap_const_lv20_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_0_preg = sub_ln1118_fu_172_p2.read().range(21, 2);
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_10_preg = ap_const_lv20_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_10_preg = sub_ln1118_10_fu_492_p2.read().range(21, 2);
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_11_preg = ap_const_lv20_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_11_preg = sub_ln1118_11_fu_524_p2.read().range(21, 2);
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_12_preg = ap_const_lv20_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_12_preg = sub_ln1118_12_fu_556_p2.read().range(21, 2);
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_13_preg = ap_const_lv20_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_13_preg = sub_ln1118_13_fu_588_p2.read().range(21, 2);
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_14_preg = ap_const_lv20_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_14_preg = sub_ln1118_14_fu_620_p2.read().range(21, 2);
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_1_preg = ap_const_lv20_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_1_preg = sub_ln1118_1_fu_204_p2.read().range(21, 2);
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_2_preg = ap_const_lv20_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_2_preg = sub_ln1118_2_fu_236_p2.read().range(21, 2);
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_3_preg = ap_const_lv20_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_3_preg = sub_ln1118_3_fu_268_p2.read().range(21, 2);
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_4_preg = ap_const_lv20_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_4_preg = sub_ln1118_4_fu_300_p2.read().range(21, 2);
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_5_preg = ap_const_lv20_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_5_preg = sub_ln1118_5_fu_332_p2.read().range(21, 2);
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_6_preg = ap_const_lv20_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_6_preg = sub_ln1118_6_fu_364_p2.read().range(21, 2);
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_7_preg = ap_const_lv20_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_7_preg = sub_ln1118_7_fu_396_p2.read().range(21, 2);
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_8_preg = ap_const_lv20_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_8_preg = sub_ln1118_8_fu_428_p2.read().range(21, 2);
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_9_preg = ap_const_lv20_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_9_preg = sub_ln1118_9_fu_460_p2.read().range(21, 2);
        }
    }
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_return_0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_0 = sub_ln1118_fu_172_p2.read().range(21, 2);
    } else {
        ap_return_0 = ap_return_0_preg.read();
    }
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_return_1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_1 = sub_ln1118_1_fu_204_p2.read().range(21, 2);
    } else {
        ap_return_1 = ap_return_1_preg.read();
    }
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_return_10() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_10 = sub_ln1118_10_fu_492_p2.read().range(21, 2);
    } else {
        ap_return_10 = ap_return_10_preg.read();
    }
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_return_11() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_11 = sub_ln1118_11_fu_524_p2.read().range(21, 2);
    } else {
        ap_return_11 = ap_return_11_preg.read();
    }
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_return_12() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_12 = sub_ln1118_12_fu_556_p2.read().range(21, 2);
    } else {
        ap_return_12 = ap_return_12_preg.read();
    }
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_return_13() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_13 = sub_ln1118_13_fu_588_p2.read().range(21, 2);
    } else {
        ap_return_13 = ap_return_13_preg.read();
    }
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_return_14() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_14 = sub_ln1118_14_fu_620_p2.read().range(21, 2);
    } else {
        ap_return_14 = ap_return_14_preg.read();
    }
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_return_2() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_2 = sub_ln1118_2_fu_236_p2.read().range(21, 2);
    } else {
        ap_return_2 = ap_return_2_preg.read();
    }
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_return_3() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_3 = sub_ln1118_3_fu_268_p2.read().range(21, 2);
    } else {
        ap_return_3 = ap_return_3_preg.read();
    }
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_return_4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_4 = sub_ln1118_4_fu_300_p2.read().range(21, 2);
    } else {
        ap_return_4 = ap_return_4_preg.read();
    }
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_return_5() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_5 = sub_ln1118_5_fu_332_p2.read().range(21, 2);
    } else {
        ap_return_5 = ap_return_5_preg.read();
    }
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_return_6() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_6 = sub_ln1118_6_fu_364_p2.read().range(21, 2);
    } else {
        ap_return_6 = ap_return_6_preg.read();
    }
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_return_7() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_7 = sub_ln1118_7_fu_396_p2.read().range(21, 2);
    } else {
        ap_return_7 = ap_return_7_preg.read();
    }
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_return_8() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_8 = sub_ln1118_8_fu_428_p2.read().range(21, 2);
    } else {
        ap_return_8 = ap_return_8_preg.read();
    }
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_return_9() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_9 = sub_ln1118_9_fu_460_p2.read().range(21, 2);
    } else {
        ap_return_9 = ap_return_9_preg.read();
    }
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_10_fu_476_p0() {
    sext_ln1118_10_fu_476_p0 = p_read10.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_10_fu_476_p1() {
    sext_ln1118_10_fu_476_p1 = esl_sext<22,20>(sext_ln1118_10_fu_476_p0.read());
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_11_fu_508_p0() {
    sext_ln1118_11_fu_508_p0 = p_read11.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_11_fu_508_p1() {
    sext_ln1118_11_fu_508_p1 = esl_sext<22,20>(sext_ln1118_11_fu_508_p0.read());
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_12_fu_540_p0() {
    sext_ln1118_12_fu_540_p0 = p_read12.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_12_fu_540_p1() {
    sext_ln1118_12_fu_540_p1 = esl_sext<22,20>(sext_ln1118_12_fu_540_p0.read());
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_13_fu_572_p0() {
    sext_ln1118_13_fu_572_p0 = p_read13.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_13_fu_572_p1() {
    sext_ln1118_13_fu_572_p1 = esl_sext<22,20>(sext_ln1118_13_fu_572_p0.read());
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_14_fu_604_p0() {
    sext_ln1118_14_fu_604_p0 = p_read14.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_14_fu_604_p1() {
    sext_ln1118_14_fu_604_p1 = esl_sext<22,20>(sext_ln1118_14_fu_604_p0.read());
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_1_fu_188_p0() {
    sext_ln1118_1_fu_188_p0 = p_read1.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_1_fu_188_p1() {
    sext_ln1118_1_fu_188_p1 = esl_sext<22,20>(sext_ln1118_1_fu_188_p0.read());
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_2_fu_220_p0() {
    sext_ln1118_2_fu_220_p0 = p_read2.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_2_fu_220_p1() {
    sext_ln1118_2_fu_220_p1 = esl_sext<22,20>(sext_ln1118_2_fu_220_p0.read());
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_3_fu_252_p0() {
    sext_ln1118_3_fu_252_p0 = p_read3.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_3_fu_252_p1() {
    sext_ln1118_3_fu_252_p1 = esl_sext<22,20>(sext_ln1118_3_fu_252_p0.read());
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_4_fu_284_p0() {
    sext_ln1118_4_fu_284_p0 = p_read4.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_4_fu_284_p1() {
    sext_ln1118_4_fu_284_p1 = esl_sext<22,20>(sext_ln1118_4_fu_284_p0.read());
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_5_fu_316_p0() {
    sext_ln1118_5_fu_316_p0 = p_read5.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_5_fu_316_p1() {
    sext_ln1118_5_fu_316_p1 = esl_sext<22,20>(sext_ln1118_5_fu_316_p0.read());
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_6_fu_348_p0() {
    sext_ln1118_6_fu_348_p0 = p_read6.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_6_fu_348_p1() {
    sext_ln1118_6_fu_348_p1 = esl_sext<22,20>(sext_ln1118_6_fu_348_p0.read());
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_7_fu_380_p0() {
    sext_ln1118_7_fu_380_p0 = p_read7.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_7_fu_380_p1() {
    sext_ln1118_7_fu_380_p1 = esl_sext<22,20>(sext_ln1118_7_fu_380_p0.read());
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_8_fu_412_p0() {
    sext_ln1118_8_fu_412_p0 = p_read8.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_8_fu_412_p1() {
    sext_ln1118_8_fu_412_p1 = esl_sext<22,20>(sext_ln1118_8_fu_412_p0.read());
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_9_fu_444_p0() {
    sext_ln1118_9_fu_444_p0 = p_read9.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_9_fu_444_p1() {
    sext_ln1118_9_fu_444_p1 = esl_sext<22,20>(sext_ln1118_9_fu_444_p0.read());
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_fu_156_p0() {
    sext_ln1118_fu_156_p0 = p_read.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sext_ln1118_fu_156_p1() {
    sext_ln1118_fu_156_p1 = esl_sext<22,20>(sext_ln1118_fu_156_p0.read());
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_shl_ln1118_10_fu_516_p3() {
    shl_ln1118_10_fu_516_p3 = esl_concat<12,10>(trunc_ln1118_11_fu_512_p1.read(), ap_const_lv10_0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_shl_ln1118_11_fu_548_p3() {
    shl_ln1118_11_fu_548_p3 = esl_concat<12,10>(trunc_ln1118_12_fu_544_p1.read(), ap_const_lv10_0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_shl_ln1118_12_fu_580_p3() {
    shl_ln1118_12_fu_580_p3 = esl_concat<12,10>(trunc_ln1118_13_fu_576_p1.read(), ap_const_lv10_0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_shl_ln1118_13_fu_612_p3() {
    shl_ln1118_13_fu_612_p3 = esl_concat<12,10>(trunc_ln1118_14_fu_608_p1.read(), ap_const_lv10_0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_shl_ln1118_1_fu_196_p3() {
    shl_ln1118_1_fu_196_p3 = esl_concat<12,10>(trunc_ln1118_1_fu_192_p1.read(), ap_const_lv10_0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_shl_ln1118_2_fu_228_p3() {
    shl_ln1118_2_fu_228_p3 = esl_concat<12,10>(trunc_ln1118_2_fu_224_p1.read(), ap_const_lv10_0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_shl_ln1118_3_fu_260_p3() {
    shl_ln1118_3_fu_260_p3 = esl_concat<12,10>(trunc_ln1118_3_fu_256_p1.read(), ap_const_lv10_0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_shl_ln1118_4_fu_292_p3() {
    shl_ln1118_4_fu_292_p3 = esl_concat<12,10>(trunc_ln1118_4_fu_288_p1.read(), ap_const_lv10_0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_shl_ln1118_5_fu_324_p3() {
    shl_ln1118_5_fu_324_p3 = esl_concat<12,10>(trunc_ln1118_5_fu_320_p1.read(), ap_const_lv10_0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_shl_ln1118_6_fu_356_p3() {
    shl_ln1118_6_fu_356_p3 = esl_concat<12,10>(trunc_ln1118_6_fu_352_p1.read(), ap_const_lv10_0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_shl_ln1118_7_fu_388_p3() {
    shl_ln1118_7_fu_388_p3 = esl_concat<12,10>(trunc_ln1118_7_fu_384_p1.read(), ap_const_lv10_0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_shl_ln1118_8_fu_420_p3() {
    shl_ln1118_8_fu_420_p3 = esl_concat<12,10>(trunc_ln1118_8_fu_416_p1.read(), ap_const_lv10_0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_shl_ln1118_9_fu_452_p3() {
    shl_ln1118_9_fu_452_p3 = esl_concat<12,10>(trunc_ln1118_9_fu_448_p1.read(), ap_const_lv10_0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_shl_ln1118_s_fu_484_p3() {
    shl_ln1118_s_fu_484_p3 = esl_concat<12,10>(trunc_ln1118_10_fu_480_p1.read(), ap_const_lv10_0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_shl_ln_fu_164_p3() {
    shl_ln_fu_164_p3 = esl_concat<12,10>(trunc_ln1118_fu_160_p1.read(), ap_const_lv10_0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sub_ln1118_10_fu_492_p2() {
    sub_ln1118_10_fu_492_p2 = (!shl_ln1118_s_fu_484_p3.read().is_01() || !sext_ln1118_10_fu_476_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(shl_ln1118_s_fu_484_p3.read()) - sc_bigint<22>(sext_ln1118_10_fu_476_p1.read()));
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sub_ln1118_11_fu_524_p2() {
    sub_ln1118_11_fu_524_p2 = (!shl_ln1118_10_fu_516_p3.read().is_01() || !sext_ln1118_11_fu_508_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(shl_ln1118_10_fu_516_p3.read()) - sc_bigint<22>(sext_ln1118_11_fu_508_p1.read()));
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sub_ln1118_12_fu_556_p2() {
    sub_ln1118_12_fu_556_p2 = (!shl_ln1118_11_fu_548_p3.read().is_01() || !sext_ln1118_12_fu_540_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(shl_ln1118_11_fu_548_p3.read()) - sc_bigint<22>(sext_ln1118_12_fu_540_p1.read()));
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sub_ln1118_13_fu_588_p2() {
    sub_ln1118_13_fu_588_p2 = (!shl_ln1118_12_fu_580_p3.read().is_01() || !sext_ln1118_13_fu_572_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(shl_ln1118_12_fu_580_p3.read()) - sc_bigint<22>(sext_ln1118_13_fu_572_p1.read()));
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sub_ln1118_14_fu_620_p2() {
    sub_ln1118_14_fu_620_p2 = (!shl_ln1118_13_fu_612_p3.read().is_01() || !sext_ln1118_14_fu_604_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(shl_ln1118_13_fu_612_p3.read()) - sc_bigint<22>(sext_ln1118_14_fu_604_p1.read()));
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sub_ln1118_1_fu_204_p2() {
    sub_ln1118_1_fu_204_p2 = (!shl_ln1118_1_fu_196_p3.read().is_01() || !sext_ln1118_1_fu_188_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(shl_ln1118_1_fu_196_p3.read()) - sc_bigint<22>(sext_ln1118_1_fu_188_p1.read()));
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sub_ln1118_2_fu_236_p2() {
    sub_ln1118_2_fu_236_p2 = (!shl_ln1118_2_fu_228_p3.read().is_01() || !sext_ln1118_2_fu_220_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(shl_ln1118_2_fu_228_p3.read()) - sc_bigint<22>(sext_ln1118_2_fu_220_p1.read()));
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sub_ln1118_3_fu_268_p2() {
    sub_ln1118_3_fu_268_p2 = (!shl_ln1118_3_fu_260_p3.read().is_01() || !sext_ln1118_3_fu_252_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(shl_ln1118_3_fu_260_p3.read()) - sc_bigint<22>(sext_ln1118_3_fu_252_p1.read()));
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sub_ln1118_4_fu_300_p2() {
    sub_ln1118_4_fu_300_p2 = (!shl_ln1118_4_fu_292_p3.read().is_01() || !sext_ln1118_4_fu_284_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(shl_ln1118_4_fu_292_p3.read()) - sc_bigint<22>(sext_ln1118_4_fu_284_p1.read()));
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sub_ln1118_5_fu_332_p2() {
    sub_ln1118_5_fu_332_p2 = (!shl_ln1118_5_fu_324_p3.read().is_01() || !sext_ln1118_5_fu_316_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(shl_ln1118_5_fu_324_p3.read()) - sc_bigint<22>(sext_ln1118_5_fu_316_p1.read()));
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sub_ln1118_6_fu_364_p2() {
    sub_ln1118_6_fu_364_p2 = (!shl_ln1118_6_fu_356_p3.read().is_01() || !sext_ln1118_6_fu_348_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(shl_ln1118_6_fu_356_p3.read()) - sc_bigint<22>(sext_ln1118_6_fu_348_p1.read()));
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sub_ln1118_7_fu_396_p2() {
    sub_ln1118_7_fu_396_p2 = (!shl_ln1118_7_fu_388_p3.read().is_01() || !sext_ln1118_7_fu_380_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(shl_ln1118_7_fu_388_p3.read()) - sc_bigint<22>(sext_ln1118_7_fu_380_p1.read()));
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sub_ln1118_8_fu_428_p2() {
    sub_ln1118_8_fu_428_p2 = (!shl_ln1118_8_fu_420_p3.read().is_01() || !sext_ln1118_8_fu_412_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(shl_ln1118_8_fu_420_p3.read()) - sc_bigint<22>(sext_ln1118_8_fu_412_p1.read()));
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sub_ln1118_9_fu_460_p2() {
    sub_ln1118_9_fu_460_p2 = (!shl_ln1118_9_fu_452_p3.read().is_01() || !sext_ln1118_9_fu_444_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(shl_ln1118_9_fu_452_p3.read()) - sc_bigint<22>(sext_ln1118_9_fu_444_p1.read()));
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_sub_ln1118_fu_172_p2() {
    sub_ln1118_fu_172_p2 = (!shl_ln_fu_164_p3.read().is_01() || !sext_ln1118_fu_156_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(shl_ln_fu_164_p3.read()) - sc_bigint<22>(sext_ln1118_fu_156_p1.read()));
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_10_fu_480_p0() {
    trunc_ln1118_10_fu_480_p0 = p_read10.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_10_fu_480_p1() {
    trunc_ln1118_10_fu_480_p1 = trunc_ln1118_10_fu_480_p0.read().range(12-1, 0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_11_fu_512_p0() {
    trunc_ln1118_11_fu_512_p0 = p_read11.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_11_fu_512_p1() {
    trunc_ln1118_11_fu_512_p1 = trunc_ln1118_11_fu_512_p0.read().range(12-1, 0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_12_fu_544_p0() {
    trunc_ln1118_12_fu_544_p0 = p_read12.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_12_fu_544_p1() {
    trunc_ln1118_12_fu_544_p1 = trunc_ln1118_12_fu_544_p0.read().range(12-1, 0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_13_fu_576_p0() {
    trunc_ln1118_13_fu_576_p0 = p_read13.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_13_fu_576_p1() {
    trunc_ln1118_13_fu_576_p1 = trunc_ln1118_13_fu_576_p0.read().range(12-1, 0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_14_fu_608_p0() {
    trunc_ln1118_14_fu_608_p0 = p_read14.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_14_fu_608_p1() {
    trunc_ln1118_14_fu_608_p1 = trunc_ln1118_14_fu_608_p0.read().range(12-1, 0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_1_fu_192_p0() {
    trunc_ln1118_1_fu_192_p0 = p_read1.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_1_fu_192_p1() {
    trunc_ln1118_1_fu_192_p1 = trunc_ln1118_1_fu_192_p0.read().range(12-1, 0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_2_fu_224_p0() {
    trunc_ln1118_2_fu_224_p0 = p_read2.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_2_fu_224_p1() {
    trunc_ln1118_2_fu_224_p1 = trunc_ln1118_2_fu_224_p0.read().range(12-1, 0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_3_fu_256_p0() {
    trunc_ln1118_3_fu_256_p0 = p_read3.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_3_fu_256_p1() {
    trunc_ln1118_3_fu_256_p1 = trunc_ln1118_3_fu_256_p0.read().range(12-1, 0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_4_fu_288_p0() {
    trunc_ln1118_4_fu_288_p0 = p_read4.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_4_fu_288_p1() {
    trunc_ln1118_4_fu_288_p1 = trunc_ln1118_4_fu_288_p0.read().range(12-1, 0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_5_fu_320_p0() {
    trunc_ln1118_5_fu_320_p0 = p_read5.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_5_fu_320_p1() {
    trunc_ln1118_5_fu_320_p1 = trunc_ln1118_5_fu_320_p0.read().range(12-1, 0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_6_fu_352_p0() {
    trunc_ln1118_6_fu_352_p0 = p_read6.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_6_fu_352_p1() {
    trunc_ln1118_6_fu_352_p1 = trunc_ln1118_6_fu_352_p0.read().range(12-1, 0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_7_fu_384_p0() {
    trunc_ln1118_7_fu_384_p0 = p_read7.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_7_fu_384_p1() {
    trunc_ln1118_7_fu_384_p1 = trunc_ln1118_7_fu_384_p0.read().range(12-1, 0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_8_fu_416_p0() {
    trunc_ln1118_8_fu_416_p0 = p_read8.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_8_fu_416_p1() {
    trunc_ln1118_8_fu_416_p1 = trunc_ln1118_8_fu_416_p0.read().range(12-1, 0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_9_fu_448_p0() {
    trunc_ln1118_9_fu_448_p0 = p_read9.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_9_fu_448_p1() {
    trunc_ln1118_9_fu_448_p1 = trunc_ln1118_9_fu_448_p0.read().range(12-1, 0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_fu_160_p0() {
    trunc_ln1118_fu_160_p0 = p_read.read();
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_trunc_ln1118_fu_160_p1() {
    trunc_ln1118_fu_160_p1 = trunc_ln1118_fu_160_p0.read().range(12-1, 0);
}

void normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

