-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    data_0_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    data_1_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    data_2_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    data_3_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    data_4_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    data_5_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    data_6_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    data_7_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    data_8_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    data_9_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    data_10_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    data_11_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    data_12_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    data_13_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    data_14_V_read : IN STD_LOGIC_VECTOR (4 downto 0) );
end;


architecture behav of dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal w_index_fu_666_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_phi_mux_do_init_phi_fu_166_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal do_init_reg_162 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_fu_672_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal data_0_V_read2_rewind_reg_177 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal data_1_V_read3_rewind_reg_191 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal data_2_V_read4_rewind_reg_205 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal data_3_V_read5_rewind_reg_219 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal data_4_V_read6_rewind_reg_233 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal data_5_V_read7_rewind_reg_247 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal data_6_V_read8_rewind_reg_261 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal data_7_V_read9_rewind_reg_275 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal data_8_V_read10_rewind_reg_289 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal data_9_V_read11_rewind_reg_303 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal data_10_V_read12_rewind_reg_317 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal data_11_V_read13_rewind_reg_331 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal data_12_V_read14_rewind_reg_345 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal data_13_V_read15_rewind_reg_359 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal data_14_V_read16_rewind_reg_373 : STD_LOGIC_VECTOR (4 downto 0);
    signal w_index1_reg_387 : STD_LOGIC_VECTOR (1 downto 0);
    signal phi_ln_fu_596_p6 : STD_LOGIC_VECTOR (4 downto 0);
    signal phi_ln77_1_fu_610_p6 : STD_LOGIC_VECTOR (4 downto 0);
    signal phi_ln77_2_fu_624_p6 : STD_LOGIC_VECTOR (4 downto 0);
    signal phi_ln77_3_fu_638_p6 : STD_LOGIC_VECTOR (4 downto 0);
    signal phi_ln77_4_fu_652_p6 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);

    component myproject_mux_42_5_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        din2 : IN STD_LOGIC_VECTOR (4 downto 0);
        din3 : IN STD_LOGIC_VECTOR (4 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;



begin
    myproject_mux_42_5_1_1_U69 : component myproject_mux_42_5_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 5,
        din2_WIDTH => 5,
        din3_WIDTH => 5,
        din4_WIDTH => 2,
        dout_WIDTH => 5)
    port map (
        din0 => ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4,
        din1 => ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4,
        din2 => ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4,
        din3 => ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4,
        din4 => w_index1_reg_387,
        dout => phi_ln_fu_596_p6);

    myproject_mux_42_5_1_1_U70 : component myproject_mux_42_5_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 5,
        din2_WIDTH => 5,
        din3_WIDTH => 5,
        din4_WIDTH => 2,
        dout_WIDTH => 5)
    port map (
        din0 => ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4,
        din1 => ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4,
        din2 => ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4,
        din3 => ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4,
        din4 => w_index1_reg_387,
        dout => phi_ln77_1_fu_610_p6);

    myproject_mux_42_5_1_1_U71 : component myproject_mux_42_5_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 5,
        din2_WIDTH => 5,
        din3_WIDTH => 5,
        din4_WIDTH => 2,
        dout_WIDTH => 5)
    port map (
        din0 => ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4,
        din1 => ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4,
        din2 => ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4,
        din3 => ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4,
        din4 => w_index1_reg_387,
        dout => phi_ln77_2_fu_624_p6);

    myproject_mux_42_5_1_1_U72 : component myproject_mux_42_5_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 5,
        din2_WIDTH => 5,
        din3_WIDTH => 5,
        din4_WIDTH => 2,
        dout_WIDTH => 5)
    port map (
        din0 => ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4,
        din1 => ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4,
        din2 => ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4,
        din3 => ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4,
        din4 => w_index1_reg_387,
        dout => phi_ln77_3_fu_638_p6);

    myproject_mux_42_5_1_1_U73 : component myproject_mux_42_5_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 5,
        din2_WIDTH => 5,
        din3_WIDTH => 5,
        din4_WIDTH => 2,
        dout_WIDTH => 5)
    port map (
        din0 => ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4,
        din1 => ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4,
        din2 => ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4,
        din3 => ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4,
        din4 => w_index1_reg_387,
        dout => phi_ln77_4_fu_652_p6);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    do_init_reg_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (icmp_ln64_fu_672_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                do_init_reg_162 <= ap_const_lv1_0;
            elsif ((((ap_start = ap_const_logic_1) and (icmp_ln64_fu_672_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                do_init_reg_162 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    w_index1_reg_387_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (icmp_ln64_fu_672_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                w_index1_reg_387 <= w_index_fu_666_p2;
            elsif ((((ap_start = ap_const_logic_1) and (icmp_ln64_fu_672_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                w_index1_reg_387 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (icmp_ln64_fu_672_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_0_V_read2_rewind_reg_177 <= ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4;
                data_10_V_read12_rewind_reg_317 <= ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4;
                data_11_V_read13_rewind_reg_331 <= ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4;
                data_12_V_read14_rewind_reg_345 <= ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4;
                data_13_V_read15_rewind_reg_359 <= ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4;
                data_14_V_read16_rewind_reg_373 <= ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4;
                data_1_V_read3_rewind_reg_191 <= ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4;
                data_2_V_read4_rewind_reg_205 <= ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4;
                data_3_V_read5_rewind_reg_219 <= ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4;
                data_4_V_read6_rewind_reg_233 <= ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4;
                data_5_V_read7_rewind_reg_247 <= ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4;
                data_6_V_read8_rewind_reg_261 <= ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4;
                data_7_V_read9_rewind_reg_275 <= ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4;
                data_8_V_read10_rewind_reg_289 <= ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4;
                data_9_V_read11_rewind_reg_303 <= ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln64_fu_672_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_start = ap_const_logic_1) and (icmp_ln64_fu_672_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln64_fu_672_p2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (icmp_ln64_fu_672_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4_assign_proc : process(data_0_V_read, ap_CS_fsm_state2, ap_phi_mux_do_init_phi_fu_166_p6, data_0_V_read2_rewind_reg_177)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_0)) then 
                ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4 <= data_0_V_read2_rewind_reg_177;
            elsif ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_1)) then 
                ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4 <= data_0_V_read;
            else 
                ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4 <= "XXXXX";
            end if;
        else 
            ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4 <= "XXXXX";
        end if; 
    end process;


    ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4_assign_proc : process(data_10_V_read, ap_CS_fsm_state2, ap_phi_mux_do_init_phi_fu_166_p6, data_10_V_read12_rewind_reg_317)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_0)) then 
                ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4 <= data_10_V_read12_rewind_reg_317;
            elsif ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_1)) then 
                ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4 <= data_10_V_read;
            else 
                ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4 <= "XXXXX";
            end if;
        else 
            ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4 <= "XXXXX";
        end if; 
    end process;


    ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4_assign_proc : process(data_11_V_read, ap_CS_fsm_state2, ap_phi_mux_do_init_phi_fu_166_p6, data_11_V_read13_rewind_reg_331)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_0)) then 
                ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4 <= data_11_V_read13_rewind_reg_331;
            elsif ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_1)) then 
                ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4 <= data_11_V_read;
            else 
                ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4 <= "XXXXX";
            end if;
        else 
            ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4 <= "XXXXX";
        end if; 
    end process;


    ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4_assign_proc : process(data_12_V_read, ap_CS_fsm_state2, ap_phi_mux_do_init_phi_fu_166_p6, data_12_V_read14_rewind_reg_345)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_0)) then 
                ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4 <= data_12_V_read14_rewind_reg_345;
            elsif ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_1)) then 
                ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4 <= data_12_V_read;
            else 
                ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4 <= "XXXXX";
            end if;
        else 
            ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4 <= "XXXXX";
        end if; 
    end process;


    ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4_assign_proc : process(data_13_V_read, ap_CS_fsm_state2, ap_phi_mux_do_init_phi_fu_166_p6, data_13_V_read15_rewind_reg_359)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_0)) then 
                ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4 <= data_13_V_read15_rewind_reg_359;
            elsif ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_1)) then 
                ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4 <= data_13_V_read;
            else 
                ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4 <= "XXXXX";
            end if;
        else 
            ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4 <= "XXXXX";
        end if; 
    end process;


    ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4_assign_proc : process(data_14_V_read, ap_CS_fsm_state2, ap_phi_mux_do_init_phi_fu_166_p6, data_14_V_read16_rewind_reg_373)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_0)) then 
                ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4 <= data_14_V_read16_rewind_reg_373;
            elsif ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_1)) then 
                ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4 <= data_14_V_read;
            else 
                ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4 <= "XXXXX";
            end if;
        else 
            ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4 <= "XXXXX";
        end if; 
    end process;


    ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4_assign_proc : process(data_1_V_read, ap_CS_fsm_state2, ap_phi_mux_do_init_phi_fu_166_p6, data_1_V_read3_rewind_reg_191)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_0)) then 
                ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4 <= data_1_V_read3_rewind_reg_191;
            elsif ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_1)) then 
                ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4 <= data_1_V_read;
            else 
                ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4 <= "XXXXX";
            end if;
        else 
            ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4 <= "XXXXX";
        end if; 
    end process;


    ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4_assign_proc : process(data_2_V_read, ap_CS_fsm_state2, ap_phi_mux_do_init_phi_fu_166_p6, data_2_V_read4_rewind_reg_205)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_0)) then 
                ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4 <= data_2_V_read4_rewind_reg_205;
            elsif ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_1)) then 
                ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4 <= data_2_V_read;
            else 
                ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4 <= "XXXXX";
            end if;
        else 
            ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4 <= "XXXXX";
        end if; 
    end process;


    ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4_assign_proc : process(data_3_V_read, ap_CS_fsm_state2, ap_phi_mux_do_init_phi_fu_166_p6, data_3_V_read5_rewind_reg_219)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_0)) then 
                ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4 <= data_3_V_read5_rewind_reg_219;
            elsif ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_1)) then 
                ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4 <= data_3_V_read;
            else 
                ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4 <= "XXXXX";
            end if;
        else 
            ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4 <= "XXXXX";
        end if; 
    end process;


    ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4_assign_proc : process(data_4_V_read, ap_CS_fsm_state2, ap_phi_mux_do_init_phi_fu_166_p6, data_4_V_read6_rewind_reg_233)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_0)) then 
                ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4 <= data_4_V_read6_rewind_reg_233;
            elsif ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_1)) then 
                ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4 <= data_4_V_read;
            else 
                ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4 <= "XXXXX";
            end if;
        else 
            ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4 <= "XXXXX";
        end if; 
    end process;


    ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4_assign_proc : process(data_5_V_read, ap_CS_fsm_state2, ap_phi_mux_do_init_phi_fu_166_p6, data_5_V_read7_rewind_reg_247)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_0)) then 
                ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4 <= data_5_V_read7_rewind_reg_247;
            elsif ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_1)) then 
                ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4 <= data_5_V_read;
            else 
                ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4 <= "XXXXX";
            end if;
        else 
            ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4 <= "XXXXX";
        end if; 
    end process;


    ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4_assign_proc : process(data_6_V_read, ap_CS_fsm_state2, ap_phi_mux_do_init_phi_fu_166_p6, data_6_V_read8_rewind_reg_261)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_0)) then 
                ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4 <= data_6_V_read8_rewind_reg_261;
            elsif ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_1)) then 
                ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4 <= data_6_V_read;
            else 
                ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4 <= "XXXXX";
            end if;
        else 
            ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4 <= "XXXXX";
        end if; 
    end process;


    ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4_assign_proc : process(data_7_V_read, ap_CS_fsm_state2, ap_phi_mux_do_init_phi_fu_166_p6, data_7_V_read9_rewind_reg_275)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_0)) then 
                ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4 <= data_7_V_read9_rewind_reg_275;
            elsif ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_1)) then 
                ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4 <= data_7_V_read;
            else 
                ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4 <= "XXXXX";
            end if;
        else 
            ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4 <= "XXXXX";
        end if; 
    end process;


    ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4_assign_proc : process(data_8_V_read, ap_CS_fsm_state2, ap_phi_mux_do_init_phi_fu_166_p6, data_8_V_read10_rewind_reg_289)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_0)) then 
                ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4 <= data_8_V_read10_rewind_reg_289;
            elsif ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_1)) then 
                ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4 <= data_8_V_read;
            else 
                ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4 <= "XXXXX";
            end if;
        else 
            ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4 <= "XXXXX";
        end if; 
    end process;


    ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4_assign_proc : process(data_9_V_read, ap_CS_fsm_state2, ap_phi_mux_do_init_phi_fu_166_p6, data_9_V_read11_rewind_reg_303)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_0)) then 
                ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4 <= data_9_V_read11_rewind_reg_303;
            elsif ((ap_phi_mux_do_init_phi_fu_166_p6 = ap_const_lv1_1)) then 
                ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4 <= data_9_V_read;
            else 
                ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4 <= "XXXXX";
            end if;
        else 
            ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4 <= "XXXXX";
        end if; 
    end process;

    ap_phi_mux_do_init_phi_fu_166_p6 <= do_init_reg_162;

    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_state2, icmp_ln64_fu_672_p2)
    begin
        if (((ap_start = ap_const_logic_1) and (icmp_ln64_fu_672_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln64_fu_672_p2 <= "1" when (w_index1_reg_387 = ap_const_lv2_2) else "0";
    w_index_fu_666_p2 <= std_logic_vector(unsigned(w_index1_reg_387) + unsigned(ap_const_lv2_1));
end behav;
