// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::ap_ST_fsm_state1 = "1";
const sc_lv<2> dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::ap_ST_fsm_state2 = "10";
const sc_lv<32> dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::ap_const_lv32_1 = "1";
const sc_lv<1> dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::ap_const_lv1_1 = "1";
const sc_lv<1> dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::ap_const_lv1_0 = "0";
const sc_lv<2> dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::ap_const_lv2_0 = "00";
const sc_lv<2> dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::ap_const_lv2_1 = "1";
const sc_lv<2> dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::ap_const_lv2_2 = "10";
const bool dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::ap_const_boolean_1 = true;

dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    myproject_mux_42_5_1_1_U69 = new myproject_mux_42_5_1_1<1,1,5,5,5,5,2,5>("myproject_mux_42_5_1_1_U69");
    myproject_mux_42_5_1_1_U69->din0(ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4);
    myproject_mux_42_5_1_1_U69->din1(ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4);
    myproject_mux_42_5_1_1_U69->din2(ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4);
    myproject_mux_42_5_1_1_U69->din3(ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4);
    myproject_mux_42_5_1_1_U69->din4(w_index1_reg_387);
    myproject_mux_42_5_1_1_U69->dout(phi_ln_fu_596_p6);
    myproject_mux_42_5_1_1_U70 = new myproject_mux_42_5_1_1<1,1,5,5,5,5,2,5>("myproject_mux_42_5_1_1_U70");
    myproject_mux_42_5_1_1_U70->din0(ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4);
    myproject_mux_42_5_1_1_U70->din1(ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4);
    myproject_mux_42_5_1_1_U70->din2(ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4);
    myproject_mux_42_5_1_1_U70->din3(ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4);
    myproject_mux_42_5_1_1_U70->din4(w_index1_reg_387);
    myproject_mux_42_5_1_1_U70->dout(phi_ln77_1_fu_610_p6);
    myproject_mux_42_5_1_1_U71 = new myproject_mux_42_5_1_1<1,1,5,5,5,5,2,5>("myproject_mux_42_5_1_1_U71");
    myproject_mux_42_5_1_1_U71->din0(ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4);
    myproject_mux_42_5_1_1_U71->din1(ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4);
    myproject_mux_42_5_1_1_U71->din2(ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4);
    myproject_mux_42_5_1_1_U71->din3(ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4);
    myproject_mux_42_5_1_1_U71->din4(w_index1_reg_387);
    myproject_mux_42_5_1_1_U71->dout(phi_ln77_2_fu_624_p6);
    myproject_mux_42_5_1_1_U72 = new myproject_mux_42_5_1_1<1,1,5,5,5,5,2,5>("myproject_mux_42_5_1_1_U72");
    myproject_mux_42_5_1_1_U72->din0(ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4);
    myproject_mux_42_5_1_1_U72->din1(ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4);
    myproject_mux_42_5_1_1_U72->din2(ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4);
    myproject_mux_42_5_1_1_U72->din3(ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4);
    myproject_mux_42_5_1_1_U72->din4(w_index1_reg_387);
    myproject_mux_42_5_1_1_U72->dout(phi_ln77_3_fu_638_p6);
    myproject_mux_42_5_1_1_U73 = new myproject_mux_42_5_1_1<1,1,5,5,5,5,2,5>("myproject_mux_42_5_1_1_U73");
    myproject_mux_42_5_1_1_U73->din0(ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4);
    myproject_mux_42_5_1_1_U73->din1(ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4);
    myproject_mux_42_5_1_1_U73->din2(ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4);
    myproject_mux_42_5_1_1_U73->din3(ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4);
    myproject_mux_42_5_1_1_U73->din4(w_index1_reg_387);
    myproject_mux_42_5_1_1_U73->dout(phi_ln77_4_fu_652_p6);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln64_fu_672_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4);
    sensitive << ( data_0_V_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_phi_mux_do_init_phi_fu_166_p6 );
    sensitive << ( data_0_V_read2_rewind_reg_177 );

    SC_METHOD(thread_ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4);
    sensitive << ( data_10_V_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_phi_mux_do_init_phi_fu_166_p6 );
    sensitive << ( data_10_V_read12_rewind_reg_317 );

    SC_METHOD(thread_ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4);
    sensitive << ( data_11_V_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_phi_mux_do_init_phi_fu_166_p6 );
    sensitive << ( data_11_V_read13_rewind_reg_331 );

    SC_METHOD(thread_ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4);
    sensitive << ( data_12_V_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_phi_mux_do_init_phi_fu_166_p6 );
    sensitive << ( data_12_V_read14_rewind_reg_345 );

    SC_METHOD(thread_ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4);
    sensitive << ( data_13_V_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_phi_mux_do_init_phi_fu_166_p6 );
    sensitive << ( data_13_V_read15_rewind_reg_359 );

    SC_METHOD(thread_ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4);
    sensitive << ( data_14_V_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_phi_mux_do_init_phi_fu_166_p6 );
    sensitive << ( data_14_V_read16_rewind_reg_373 );

    SC_METHOD(thread_ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4);
    sensitive << ( data_1_V_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_phi_mux_do_init_phi_fu_166_p6 );
    sensitive << ( data_1_V_read3_rewind_reg_191 );

    SC_METHOD(thread_ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4);
    sensitive << ( data_2_V_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_phi_mux_do_init_phi_fu_166_p6 );
    sensitive << ( data_2_V_read4_rewind_reg_205 );

    SC_METHOD(thread_ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4);
    sensitive << ( data_3_V_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_phi_mux_do_init_phi_fu_166_p6 );
    sensitive << ( data_3_V_read5_rewind_reg_219 );

    SC_METHOD(thread_ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4);
    sensitive << ( data_4_V_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_phi_mux_do_init_phi_fu_166_p6 );
    sensitive << ( data_4_V_read6_rewind_reg_233 );

    SC_METHOD(thread_ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4);
    sensitive << ( data_5_V_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_phi_mux_do_init_phi_fu_166_p6 );
    sensitive << ( data_5_V_read7_rewind_reg_247 );

    SC_METHOD(thread_ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4);
    sensitive << ( data_6_V_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_phi_mux_do_init_phi_fu_166_p6 );
    sensitive << ( data_6_V_read8_rewind_reg_261 );

    SC_METHOD(thread_ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4);
    sensitive << ( data_7_V_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_phi_mux_do_init_phi_fu_166_p6 );
    sensitive << ( data_7_V_read9_rewind_reg_275 );

    SC_METHOD(thread_ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4);
    sensitive << ( data_8_V_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_phi_mux_do_init_phi_fu_166_p6 );
    sensitive << ( data_8_V_read10_rewind_reg_289 );

    SC_METHOD(thread_ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4);
    sensitive << ( data_9_V_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_phi_mux_do_init_phi_fu_166_p6 );
    sensitive << ( data_9_V_read11_rewind_reg_303 );

    SC_METHOD(thread_ap_phi_mux_do_init_phi_fu_166_p6);
    sensitive << ( do_init_reg_162 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln64_fu_672_p2 );

    SC_METHOD(thread_icmp_ln64_fu_672_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( w_index1_reg_387 );

    SC_METHOD(thread_w_index_fu_666_p2);
    sensitive << ( w_index1_reg_387 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln64_fu_672_p2 );

    ap_CS_fsm = "01";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, data_5_V_read, "(port)data_5_V_read");
    sc_trace(mVcdFile, data_6_V_read, "(port)data_6_V_read");
    sc_trace(mVcdFile, data_7_V_read, "(port)data_7_V_read");
    sc_trace(mVcdFile, data_8_V_read, "(port)data_8_V_read");
    sc_trace(mVcdFile, data_9_V_read, "(port)data_9_V_read");
    sc_trace(mVcdFile, data_10_V_read, "(port)data_10_V_read");
    sc_trace(mVcdFile, data_11_V_read, "(port)data_11_V_read");
    sc_trace(mVcdFile, data_12_V_read, "(port)data_12_V_read");
    sc_trace(mVcdFile, data_13_V_read, "(port)data_13_V_read");
    sc_trace(mVcdFile, data_14_V_read, "(port)data_14_V_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, w_index_fu_666_p2, "w_index_fu_666_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_phi_mux_do_init_phi_fu_166_p6, "ap_phi_mux_do_init_phi_fu_166_p6");
    sc_trace(mVcdFile, do_init_reg_162, "do_init_reg_162");
    sc_trace(mVcdFile, icmp_ln64_fu_672_p2, "icmp_ln64_fu_672_p2");
    sc_trace(mVcdFile, ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4, "ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4");
    sc_trace(mVcdFile, data_0_V_read2_rewind_reg_177, "data_0_V_read2_rewind_reg_177");
    sc_trace(mVcdFile, ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4, "ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4");
    sc_trace(mVcdFile, data_1_V_read3_rewind_reg_191, "data_1_V_read3_rewind_reg_191");
    sc_trace(mVcdFile, ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4, "ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4");
    sc_trace(mVcdFile, data_2_V_read4_rewind_reg_205, "data_2_V_read4_rewind_reg_205");
    sc_trace(mVcdFile, ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4, "ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4");
    sc_trace(mVcdFile, data_3_V_read5_rewind_reg_219, "data_3_V_read5_rewind_reg_219");
    sc_trace(mVcdFile, ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4, "ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4");
    sc_trace(mVcdFile, data_4_V_read6_rewind_reg_233, "data_4_V_read6_rewind_reg_233");
    sc_trace(mVcdFile, ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4, "ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4");
    sc_trace(mVcdFile, data_5_V_read7_rewind_reg_247, "data_5_V_read7_rewind_reg_247");
    sc_trace(mVcdFile, ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4, "ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4");
    sc_trace(mVcdFile, data_6_V_read8_rewind_reg_261, "data_6_V_read8_rewind_reg_261");
    sc_trace(mVcdFile, ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4, "ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4");
    sc_trace(mVcdFile, data_7_V_read9_rewind_reg_275, "data_7_V_read9_rewind_reg_275");
    sc_trace(mVcdFile, ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4, "ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4");
    sc_trace(mVcdFile, data_8_V_read10_rewind_reg_289, "data_8_V_read10_rewind_reg_289");
    sc_trace(mVcdFile, ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4, "ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4");
    sc_trace(mVcdFile, data_9_V_read11_rewind_reg_303, "data_9_V_read11_rewind_reg_303");
    sc_trace(mVcdFile, ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4, "ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4");
    sc_trace(mVcdFile, data_10_V_read12_rewind_reg_317, "data_10_V_read12_rewind_reg_317");
    sc_trace(mVcdFile, ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4, "ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4");
    sc_trace(mVcdFile, data_11_V_read13_rewind_reg_331, "data_11_V_read13_rewind_reg_331");
    sc_trace(mVcdFile, ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4, "ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4");
    sc_trace(mVcdFile, data_12_V_read14_rewind_reg_345, "data_12_V_read14_rewind_reg_345");
    sc_trace(mVcdFile, ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4, "ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4");
    sc_trace(mVcdFile, data_13_V_read15_rewind_reg_359, "data_13_V_read15_rewind_reg_359");
    sc_trace(mVcdFile, ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4, "ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4");
    sc_trace(mVcdFile, data_14_V_read16_rewind_reg_373, "data_14_V_read16_rewind_reg_373");
    sc_trace(mVcdFile, w_index1_reg_387, "w_index1_reg_387");
    sc_trace(mVcdFile, phi_ln_fu_596_p6, "phi_ln_fu_596_p6");
    sc_trace(mVcdFile, phi_ln77_1_fu_610_p6, "phi_ln77_1_fu_610_p6");
    sc_trace(mVcdFile, phi_ln77_2_fu_624_p6, "phi_ln77_2_fu_624_p6");
    sc_trace(mVcdFile, phi_ln77_3_fu_638_p6, "phi_ln77_3_fu_638_p6");
    sc_trace(mVcdFile, phi_ln77_4_fu_652_p6, "phi_ln77_4_fu_652_p6");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::~dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete myproject_mux_42_5_1_1_U69;
    delete myproject_mux_42_5_1_1_U70;
    delete myproject_mux_42_5_1_1_U71;
    delete myproject_mux_42_5_1_1_U72;
    delete myproject_mux_42_5_1_1_U73;
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln64_fu_672_p2.read()))) {
        do_init_reg_162 = ap_const_lv1_0;
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                 esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln64_fu_672_p2.read())))) {
        do_init_reg_162 = ap_const_lv1_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln64_fu_672_p2.read()))) {
        w_index1_reg_387 = w_index_fu_666_p2.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                 esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln64_fu_672_p2.read())))) {
        w_index1_reg_387 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln64_fu_672_p2.read()))) {
        data_0_V_read2_rewind_reg_177 = ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4.read();
        data_10_V_read12_rewind_reg_317 = ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4.read();
        data_11_V_read13_rewind_reg_331 = ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4.read();
        data_12_V_read14_rewind_reg_345 = ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4.read();
        data_13_V_read15_rewind_reg_359 = ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4.read();
        data_14_V_read16_rewind_reg_373 = ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4.read();
        data_1_V_read3_rewind_reg_191 = ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4.read();
        data_2_V_read4_rewind_reg_205 = ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4.read();
        data_3_V_read5_rewind_reg_219 = ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4.read();
        data_4_V_read6_rewind_reg_233 = ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4.read();
        data_5_V_read7_rewind_reg_247 = ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4.read();
        data_6_V_read8_rewind_reg_261 = ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4.read();
        data_7_V_read9_rewind_reg_275 = ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4.read();
        data_8_V_read10_rewind_reg_289 = ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4.read();
        data_9_V_read11_rewind_reg_303 = ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4.read();
    }
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln64_fu_672_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if (esl_seteq<1,1,1>(ap_phi_mux_do_init_phi_fu_166_p6.read(), ap_const_lv1_0)) {
            ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4 = data_0_V_read2_rewind_reg_177.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_do_init_phi_fu_166_p6.read())) {
            ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4 = data_0_V_read.read();
        } else {
            ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4 = "XXXXX";
        }
    } else {
        ap_phi_mux_data_0_V_read2_phi_phi_fu_405_p4 = "XXXXX";
    }
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if (esl_seteq<1,1,1>(ap_phi_mux_do_init_phi_fu_166_p6.read(), ap_const_lv1_0)) {
            ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4 = data_10_V_read12_rewind_reg_317.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_do_init_phi_fu_166_p6.read())) {
            ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4 = data_10_V_read.read();
        } else {
            ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4 = "XXXXX";
        }
    } else {
        ap_phi_mux_data_10_V_read12_phi_phi_fu_535_p4 = "XXXXX";
    }
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if (esl_seteq<1,1,1>(ap_phi_mux_do_init_phi_fu_166_p6.read(), ap_const_lv1_0)) {
            ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4 = data_11_V_read13_rewind_reg_331.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_do_init_phi_fu_166_p6.read())) {
            ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4 = data_11_V_read.read();
        } else {
            ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4 = "XXXXX";
        }
    } else {
        ap_phi_mux_data_11_V_read13_phi_phi_fu_548_p4 = "XXXXX";
    }
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if (esl_seteq<1,1,1>(ap_phi_mux_do_init_phi_fu_166_p6.read(), ap_const_lv1_0)) {
            ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4 = data_12_V_read14_rewind_reg_345.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_do_init_phi_fu_166_p6.read())) {
            ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4 = data_12_V_read.read();
        } else {
            ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4 = "XXXXX";
        }
    } else {
        ap_phi_mux_data_12_V_read14_phi_phi_fu_561_p4 = "XXXXX";
    }
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if (esl_seteq<1,1,1>(ap_phi_mux_do_init_phi_fu_166_p6.read(), ap_const_lv1_0)) {
            ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4 = data_13_V_read15_rewind_reg_359.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_do_init_phi_fu_166_p6.read())) {
            ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4 = data_13_V_read.read();
        } else {
            ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4 = "XXXXX";
        }
    } else {
        ap_phi_mux_data_13_V_read15_phi_phi_fu_574_p4 = "XXXXX";
    }
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if (esl_seteq<1,1,1>(ap_phi_mux_do_init_phi_fu_166_p6.read(), ap_const_lv1_0)) {
            ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4 = data_14_V_read16_rewind_reg_373.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_do_init_phi_fu_166_p6.read())) {
            ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4 = data_14_V_read.read();
        } else {
            ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4 = "XXXXX";
        }
    } else {
        ap_phi_mux_data_14_V_read16_phi_phi_fu_587_p4 = "XXXXX";
    }
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if (esl_seteq<1,1,1>(ap_phi_mux_do_init_phi_fu_166_p6.read(), ap_const_lv1_0)) {
            ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4 = data_1_V_read3_rewind_reg_191.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_do_init_phi_fu_166_p6.read())) {
            ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4 = data_1_V_read.read();
        } else {
            ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4 = "XXXXX";
        }
    } else {
        ap_phi_mux_data_1_V_read3_phi_phi_fu_418_p4 = "XXXXX";
    }
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if (esl_seteq<1,1,1>(ap_phi_mux_do_init_phi_fu_166_p6.read(), ap_const_lv1_0)) {
            ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4 = data_2_V_read4_rewind_reg_205.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_do_init_phi_fu_166_p6.read())) {
            ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4 = data_2_V_read.read();
        } else {
            ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4 = "XXXXX";
        }
    } else {
        ap_phi_mux_data_2_V_read4_phi_phi_fu_431_p4 = "XXXXX";
    }
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if (esl_seteq<1,1,1>(ap_phi_mux_do_init_phi_fu_166_p6.read(), ap_const_lv1_0)) {
            ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4 = data_3_V_read5_rewind_reg_219.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_do_init_phi_fu_166_p6.read())) {
            ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4 = data_3_V_read.read();
        } else {
            ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4 = "XXXXX";
        }
    } else {
        ap_phi_mux_data_3_V_read5_phi_phi_fu_444_p4 = "XXXXX";
    }
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if (esl_seteq<1,1,1>(ap_phi_mux_do_init_phi_fu_166_p6.read(), ap_const_lv1_0)) {
            ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4 = data_4_V_read6_rewind_reg_233.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_do_init_phi_fu_166_p6.read())) {
            ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4 = data_4_V_read.read();
        } else {
            ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4 = "XXXXX";
        }
    } else {
        ap_phi_mux_data_4_V_read6_phi_phi_fu_457_p4 = "XXXXX";
    }
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if (esl_seteq<1,1,1>(ap_phi_mux_do_init_phi_fu_166_p6.read(), ap_const_lv1_0)) {
            ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4 = data_5_V_read7_rewind_reg_247.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_do_init_phi_fu_166_p6.read())) {
            ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4 = data_5_V_read.read();
        } else {
            ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4 = "XXXXX";
        }
    } else {
        ap_phi_mux_data_5_V_read7_phi_phi_fu_470_p4 = "XXXXX";
    }
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if (esl_seteq<1,1,1>(ap_phi_mux_do_init_phi_fu_166_p6.read(), ap_const_lv1_0)) {
            ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4 = data_6_V_read8_rewind_reg_261.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_do_init_phi_fu_166_p6.read())) {
            ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4 = data_6_V_read.read();
        } else {
            ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4 = "XXXXX";
        }
    } else {
        ap_phi_mux_data_6_V_read8_phi_phi_fu_483_p4 = "XXXXX";
    }
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if (esl_seteq<1,1,1>(ap_phi_mux_do_init_phi_fu_166_p6.read(), ap_const_lv1_0)) {
            ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4 = data_7_V_read9_rewind_reg_275.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_do_init_phi_fu_166_p6.read())) {
            ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4 = data_7_V_read.read();
        } else {
            ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4 = "XXXXX";
        }
    } else {
        ap_phi_mux_data_7_V_read9_phi_phi_fu_496_p4 = "XXXXX";
    }
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if (esl_seteq<1,1,1>(ap_phi_mux_do_init_phi_fu_166_p6.read(), ap_const_lv1_0)) {
            ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4 = data_8_V_read10_rewind_reg_289.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_do_init_phi_fu_166_p6.read())) {
            ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4 = data_8_V_read.read();
        } else {
            ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4 = "XXXXX";
        }
    } else {
        ap_phi_mux_data_8_V_read10_phi_phi_fu_509_p4 = "XXXXX";
    }
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if (esl_seteq<1,1,1>(ap_phi_mux_do_init_phi_fu_166_p6.read(), ap_const_lv1_0)) {
            ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4 = data_9_V_read11_rewind_reg_303.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_do_init_phi_fu_166_p6.read())) {
            ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4 = data_9_V_read.read();
        } else {
            ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4 = "XXXXX";
        }
    } else {
        ap_phi_mux_data_9_V_read11_phi_phi_fu_522_p4 = "XXXXX";
    }
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_phi_mux_do_init_phi_fu_166_p6() {
    ap_phi_mux_do_init_phi_fu_166_p6 = do_init_reg_162.read();
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln64_fu_672_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_icmp_ln64_fu_672_p2() {
    icmp_ln64_fu_672_p2 = (!w_index1_reg_387.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(w_index1_reg_387.read() == ap_const_lv2_2);
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_w_index_fu_666_p2() {
    w_index_fu_666_p2 = (!w_index1_reg_387.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(w_index1_reg_387.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void dense_resource_ap_ufixed_ap_fixed_16_5_5_3_0_config6_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln64_fu_672_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<2>) ("XX");
            break;
    }
}

}

